### ISSUE TITLE
Lanterna doesn't find Monospaced font on Ubuntu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#120]
```
My Ubuntu system doesn't have a font named Monospace. Can you search for Ubuntu 
Mono, FreeMono DejaVu San Mono and Liberation Mono? Linux systems should have 
one of those.

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.googlecode.lanterna.terminal.DefaultTerminalFactory.<init>(DefaultTerminalFactory.java:83)
	at com.googlecode.lanterna.terminal.DefaultTerminalFactory.<init>(DefaultTerminalFactory.java:62)
	at com.jacobwabrams.lanterna.Main.main(Main.java:15)
Caused by: java.lang.IllegalArgumentException: Font 
java.awt.Font[family=Monospaced,name=Monospaced,style=plain,size=14] isn't 
monospaced!
	at com.googlecode.lanterna.terminal.swing.SwingTerminalFontConfiguration.<init>(SwingTerminalFontConfiguration.java:77)
	at com.googlecode.lanterna.terminal.swing.SwingTerminalFontConfiguration.newInstance(SwingTerminalFontConfiguration.java:56)
	at com.googlecode.lanterna.terminal.swing.SwingTerminalFontConfiguration.<clinit>(SwingTerminalFontConfiguration.java:39)
	... 3 more


java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)

Linux version 3.13.0-43-generic (buildd@tipua) (gcc version 4.8.2 (Ubuntu 
4.8.2-19ubuntu1) ) #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014


```

Original issue reported on code.google.com by `satur9n...@gmail.com` on 26 Dec 2014 at 5:14

**Comment by mabe02** [comment]
Lanterna 3 supports adding a list of fonts to be using with the SwingTerminal, I'm afraid you'll have to pass in whatever you prefer it to use. As a library, we can't really make any assumptions about what fonts are installed, which is why Java is supplying an alias whenever we want to find monospaced font. If Java returns a non-monospaced font for the Monospaced alias, sounds like a bug in Java to me...
