### ISSUE TITLE
Cygwin exception

### ISSUE THREAD

**Issue by gurinderu** [mabe02/lanterna#139]
OS: Windows 7 in Cygwin

Simple code: 
DefaultTerminalFactory factory = new DefaultTerminalFactory();
        factory.setSuppressSwingTerminalFrame(true);
        Screen screen = new VirtualScreen(new TerminalScreen(factory.createTerminal()));
        screen.startScreen();
        MultiWindowTextGUI textGUI = new MultiWindowTextGUI(screen);

        final BasicWindow window = new BasicWindow("Dialog test");
        textGUI.addWindow(window);

Exception in thread "main" java.io.IOException: Cannot run program "/bin/sh": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at com.googlecode.lanterna.terminal.ansi.UnixTerminal.exec(UnixTerminal.java:313)
        at com.googlecode.lanterna.terminal.ansi.UnixTerminal.saveSTTY(UnixTerminal.java:289)
        at com.googlecode.lanterna.terminal.ansi.UnixTerminal.<init>(UnixTerminal.java:158)
        at com.googlecode.lanterna.terminal.ansi.UnixTerminal.<init>(UnixTerminal.java:106)
        at com.googlecode.lanterna.terminal.ansi.UnixTerminal.<init>(UnixTerminal.java:85)
        at com.googlecode.lanterna.terminal.ansi.CygwinTerminal.<init>(CygwinTerminal.java:46)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createCygwinTerminal(DefaultTerminalFactory.java:176)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createTerminal(DefaultTerminalFactory.java:90)
        at guru.grinder.Main.main(Main.java:23)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 10 more

**Comment by avl42** [comment]
The root problem is, that UnixTerminal does more in its constructor than it should.
Therefore, all these alternatives coded in the CygwinTerminal just can't modify
base-class's (namely UnixTerminal's) construction.

To fix it, UnixTerminal ought to define a "bare" constructor to just set the fields,
but omit its Unix-specific trickery.

Then, CygwinTerminal's constructor could use that bare constructor and then
do its own trickery as necessary for cygwin.

An even better approach would be to extract certain parts of the constructor into
a separate new protected method "initTerminal()", and point out (in the docs) that
this method needs to be called after directly "new"ing any of Lanterna's Terminal
classes.
The DefaultTerminalFactory would then call initTerminal(), too, for convenience.

As it is, unless cygwin can be made to find a "/bin/sh" and appear just like Unix,
I fear that Swing-terminals are currently the only option for Windows.

**Comment by avl42** [comment]
PS: other fixes would be to have CygwinTerminal derive directly from ANSITerminal,
   or to insert a UnixishTerminal into the hierarchy between ANSI- and UnixTerminal,
   and have it do only the common stuff for Unix and cygwin.

**Comment by mabe02** [comment]
CygwinTerminal was never finished, I gave it some work a long time ago but it never worked 100%, believe I got stuck on some issue with controlling the tty...?

**Comment by avl42** [comment]
I'm already in progress of preparing a patch for it...   stay tuned for a pull-request :)

**Comment by avl42** [comment]
gurinderu: could you please test and report whether the current version on the master branch works on cygwin?

**Comment by mabe02** [comment]
I've tried it and while it's working better, there's still problems with pseudu-terminal interactions through stty. I see a new device under /dev whenever I open a new Cygwin window and calling stty.exe -F /dev/<device> does seem to be able to read the state of that terminal, but I just can not make it modify it (unless it's trying to modify itself). For example, trying to turn off echo for another terminal won't work. If the device is substituted for the own terminal, it works as expected.

**Comment by avl42** [comment]
did you mean writing just /dev/ or did github swallow something? Does java have a way to know its current terminal device? There's probably not much point in changing another terminal, anyway ;)

**Comment by mabe02** [comment]
No, my point was that it seems impossible to modify the terminal properties unless you have a direct shell in the terminal itself. So when Cygwin calls Java, which isn't cygwin-compiled, that in turn calls a cygwin compiled binary (stty.exe), it's not able to modify the terminal that originally launched the java process. That's how it seems to me right now anyhow.

**Comment by avl42** [comment]
So, for Cygwin, we'd rather remove most stty calls and suggest using a wrapper script around java that would do "stty icanon -echo min 1", then start java, then reset to "stty sane" afterwards...

**Comment by mabe02** [comment]
Yeah, that's one option. Not very elegant but shouganai I suppose. Contemplated looking up the cygwin dev mailing list (if there is such a thing) and asking them if they have any hints.

**Comment by adiantek** [comment]
On Windows:

    Exception in thread "main" java.io.IOException: Cannot run program "stty.exe": CreateProcess error=2, Nie można odnaleźć
     określonego pliku
        at java.lang.ProcessBuilder.start(Unknown Source)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal.exec(UnixLikeTerminal.java:89)
        at com.googlecode.lanterna.terminal.ansi.CygwinTerminal.runSTTYCommand(CygwinTerminal.java:124)
        at com.googlecode.lanterna.terminal.ansi.CygwinTerminal.sttySave(CygwinTerminal.java:106)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal.saveSTTY(UnixLikeTerminal.java:206)
        at com.googlecode.lanterna.terminal.ansi.CygwinTerminal.<init>(CygwinTerminal.java:65)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createCygwinTerminal(DefaultTerminalFactory.java:280)

        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createTerminal(DefaultTerminalFactory.java:96)
        at Main.main(Main.java:86)
    Caused by: java.io.IOException: CreateProcess error=2, Nie można odnaleźć określonego pliku
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 9 more

**Comment by avl42** [comment]
@adiantek
I don't know your environment. Do you even have Cygwin installed, or was it already a mistake of Lanterna to assume availability of cygwin?

With Cygwin, there are still problems on the way, but at least it should have **found** stty.exe.

If you didn't expect anything Cygwin-ish at all, then we would need to know what you did:
Did you start the application is some strange way (e.g.: from a telnet-session), or did you set any specific options on the DefaultTerminalFactory?

**Comment by adiantek** [comment]
I don't have Cygwin installed. Is it needed to lanterna on Windows?
24 mar 2016 08:42 "Andreas Leitgeb" <notifications@github.com> napisał(a):

**Comment by avl42** [comment]
Thanks for your clarification of your situation.

One does not need cygwin to use lanterna on Windows.

As it seems, something about your environment triggers a bug that makes Lanterna assume availability of cygwin. Maybe you're starting Java from a DOS prompt, or a .bat or .cmd script, rather than the beaten path of double-clicking a jar-file or running in eclipse...

Whatever you're doing probably should work, and lanterna needs to be fixed to make it work. Telling us, how you start your application could help us find a way to make it work.

**Comment by adiantek** [comment]
When I'm starting from Eclipse, it runs in Swing. When I'm running from cmd
via java -jar, it's want to run Cygwin like.
24 mar 2016 13:52 "Andreas Leitgeb" <notifications@github.com> napisał(a):

**Comment by avl42** [comment]
@mabe02  I suspect it's the availability of a System "console", so we might need to tune the heuristics better, such that if console is there, but we're on windows, then try to call stty with harmless arguments, and if that fails, then fallback to swing...

**Comment by mabe02** [comment]
There's a couple of operations, such as cbreak, that just won't work on windows (cygwin or no cygwin) without linking to native code. Thinking about extracting all that out to a separate class and then separate from lanterna distribute code using jna.

**Comment by mabe02** [comment]
Yeah, assuming cygwin when console() is present on Windows isn't ideal

**Comment by Janrupf** [comment]
Might be a little bit crazy to weite here, but this isn fixed yet. So is it work in progress or why is it not fixed. I'm having the same problem (I know, 2 years ago) and I'm using the latest build. Please fix it.

**Comment by mabe02** [comment]
This is certainly not fixed. The invoking Cygwin stty from a win32 process (java) and linking it to the correct terminal session is really difficult, I haven't been able to figure out how to do it. Do you have any ideas?

**Comment by Janrupf** [comment]
No, but maybe its easier to use natives (dll).

**Comment by Janrupf** [comment]
What is mingw's stty.exe doing. I have it installed, but I think the problem is not stty.exe itself, cause the java exception just sys that it was unable to find the programm. So `/bin/stty` ist not the Path, it's `C:\MinGW\msys\1.0\bin.stty.exe` for me. So just the path is wrong.

**Comment by Janrupf** [comment]
I fixed the problem, but now the output is a little bit messed up...
```
[?1049h[2J[?25h[1;1H[39m[49m[2J[0m[1;1H[30m[44m                                                                                [2;1H                                                                                [3;1H                                                                                [4;1H                                                                                [5;1H                                                                                [6;1H    [37m[47m[1m(0l(B(0q(B(0q(B[30m[22mJSysCloud[37m[1m(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B[30m[22m(0k(B[44m    [7;1H    [37m[47m[1m(0x(B[44m                                                           [30m[47m[22m <  [31mS[30m[1mend[22m  >(0x(B[40m[1m  [44m[22m  [8;1H    [37m[47m[1m(0x(B[30m[22m                                                                      (0x(B[40m[1m  [44m[22m  [9;1H    [37m[47m[1m(0x(B[44m[22m[19:47:54] INFO: Welcome to JSysCloud!                                [30m[47m(0x(B[40m[1m  [44m[22m  [10;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [11;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [12;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [13;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [14;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [15;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [16;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [17;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [18;1H    [37m[47m[1m(0x(B[44m[22m                                                                      [30m[47m(0x(B[40m[1m  [44m[22m  [19;1H    [37m[47m[1m(0m(B[30m[22m(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0q(B(0j(B[40m[1m  [44m[22m  [20;1H      [40m[1m                                                                        [44m[22m  [21;1H                                                                                [22;1H                                                                                [23;1H                                                                                [24;1H                                                                                [?25h[7;6H[0m[?25h[?1049l
```

**Comment by avl42** [comment]
what terminal are you running it in? cmd.exe? if so, that doesn't work
because cmd.exe is just not interpreting the escape sequences.

there are some classes that try to do native stuff on windows to get it
working in cmd.exe, but for those you need "JNA".

ps: i don't have windows on my pcs, so i'm merely telling what i read in
the past.

Am 09.07.2017 19:50 schrieb "Janrupf" <notifications@github.com>:

**Comment by Janrupf** [comment]
Jep, running in windows terminal, the problem is that windows only have this one terminal, so you can't use another one.

**Comment by avl42** [comment]
the terminal class is named "CygwinTerminal", as it is expected to be used
in some Cygwin shell window that is supposed to do ansi sequences. i don't
know if other windows-unix-kits also provide a decent "terminal"-alike. if
you need to let it run in cmd.exe, then you'll definitely need the JNA
library.

Am 09.07.2017 20:18 schrieb "Janrupf" <notifications@github.com>:

**Comment by Janrupf** [comment]
Under Windows there is only one terminal, cmd.exe. Just loading the JNA is doing nothing, so frome here the problem is cygwin. But can you explain what are you doing with cygwin?
Or what is if am writing a dll wich contain methods to set cursor position and color? 
Would it help you?

**Comment by avl42** [comment]
if JNA is available and you use the DefaultTerminalFactory to create a
Terminal, it will not use CygwinTerminal, but a windows-specific one, that
should work with cmd.exe

i can't say for sure whether it will work, but very surely mabe02 will
appreciate feedback about it, either way.



Am 09.07.2017 20:42 schrieb "Janrupf" <notifications@github.com>:

Under Windows there is only one terminal, cmd.exe. Just loading the JNA is
doing nothing, so frome here the problem is cygwin. But can you explain
what are you doing with cygwin?
Or what is if am writing a dll wich contain methods to set cursor position
and color?
Would it help you?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mabe02/lanterna/issues/139#issuecomment-313937670>, or mute
the thread

**Comment by avl42** [comment]
afternote: make sure that you include the "native" hierarchy to your IDE's
build path, too.

Am 09.07.2017 20:46 schrieb "Andreas Leitgeb" <avlplus42@gmail.com>:

**Comment by Janrupf** [comment]
Ok, I'm using Eclipse as IDE. I will take a look at JNA and the natives. But you should remember that windows is using another file system, so a path never starts with /. I

**Comment by avl42** [comment]
it's 'native-integration/src' in lanterna directory where you need to
select 'use source folder' for, unless it's preselected.  if you then get
lots of errors, then don't forget adding jna.

with that approach it won't need stty, anyway.

ps: on windows, why don't you just use the swingterminal?



Am 09.07.2017 21:08 schrieb "Janrupf" <notifications@github.com>:

Ok, I'm using Eclipse as IDE. I will take a look at JNA and the natives.
But you should remember that windows is using another file system, so a
path never starts with /. I

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mabe02/lanterna/issues/139#issuecomment-313944445>, or mute
the thread

**Comment by Janrupf** [comment]
For my self I'm using swing, but I want to publish my programm. And then its usual to start these programms with command line. And for windows server you usually starting from the command line.

**Comment by Janrupf** [comment]
I dont know how to add these uncompiled java files (the natives) in eclipse. I've donwloaded the lanterna.jar, but how can I use them now.

**Comment by Janrupf** [comment]
Ok, just integrated the natives, same output like CyGwin terminal, so looks like there are ANSI escapes.

**Comment by Janrupf** [comment]
Just implemented an way to change console color. Just wrapping `SetConsoleTextAttribute(WinDef.HANDLE hConsoleOutput, WinDef.WORD wAttributes)`.

**Comment by mabe02** [comment]
I haven't tried out the native-integration for a while now, it was working relatively well for a while but then something broke and I didn't come around to fix it.
Anyhow, running cmd.exe isn't going to work with CygwinTerminal because with CygwinTerminal we rely on the same unix utility program (stty) that the Unix terminals are using in order to change input mode and turn off echoing. cmd.exe doesn't support any of this and there isn't any other way to do those operations without calling into native code.
But I think MS did implement the basic set of ANSI escape codes so that's generally not the problem I've seen. Possibly cursor position isn't working, which will make terminal size detection problematic.

**Comment by mabe02** [comment]
Actually, now I'm confused. Reading online that Win32 cmd.exe never supported ANSI escape codes until the Win10 anniversary update, I was so sure I had actually got it working a year or two ago on windows using the jna library!
I guess not??
I've tried using the new ENABLE_VIRTUAL_TERMINAL_PROCESSING flag but still can't get it to work...
https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx

**Comment by Janrupf** [comment]
Crazy, i'm using win64 redstone2 (upgrading in a few days to creator). The ANSI system is completly messed up under windows. Looks like it isn really supporting it but creating weird characters so it  is translating something. 

Ok, so now im having big trouble with the windows console. I'm not able to translate the Textcolors to a windows friendly format. I wrote an JNI based dll for setting cursor pos and so on, but would be possible using jna cause the math things im doing is also possible with Java. 
But how should i translate the lanterna textcolors to windows colors (1-7 & A-F)?

**Comment by Janrupf** [comment]
Also interesting that windows doesnt support bold text, but we may change this with changing the cursor height. But the most sgr sequekces arent supported, weird... Dos had all this features. Ir I'm right, Dos also supported ANSI.

**Comment by Janrupf** [comment]
Sorry for writing this and not editing, but currently im using a mobile phone.  Anyway, looks like the powershell can be modified to use ansi. And launching in powershell is the same as launching in cmd. 

Here I found an powershell module: 
https://github.com/PoshCode/Pansies/blob/master/README.md

**Comment by Janrupf** [comment]
https://www.reddit.com/r/Windows10/comments/44czox/windows_10_v1511_adds_support_for_ansi_escape/

Now im confused to, just using the wrong escape character???

This is getting weird now.

**Comment by Janrupf** [comment]
Ok, I think I found a solution:

https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx

Invoking this with jna should work.

**Comment by mabe02** [comment]
Okay, I haven't had a chance to test it yet but I've put in the code

**Comment by avl42** [comment]
Rereading this thread once again, maybe the solution is to just use 'javaw.exe' instead of 'java.exe' when starting from cmd.exe or with a .bat file. That could help it still open a Swing-terminal on windows, even when started that way.

If the expectation was really to run it exactly in the cmd, then just forget this comment.

**Comment by CodeFarmer** [comment]
I am not entirely sure if this is the right issue any more (will happily open another one if not).

Even running from within Cygwin, the CygwinTerminal still can't find /bin/stty (even though it's in the Cygwin filesystem).

Ironically, I even have Cygwin's bin directory in my Windows PATH, so I can run stty from cmd :)

It seems to be trying to access the absolute path rather than reading from $PATH - and doing it in the Windows filesystem rather than from Cygwin's.

`Exception in thread "main" java.io.IOException: Cannot run program "/bin/stty": CreateProcess error=2, The system cannot find the file specified, compiling:(C:\cygwin64\tmp\form-init4253205981875632234.clj:1:87)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invokeStatic(main.clj:280)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: java.io.IOException: Cannot run program "/bin/stty": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.exec(UnixLikeTTYTerminal.java:169)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.saveTerminalSettings(UnixLikeTTYTerminal.java:117)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal.acquire(UnixLikeTerminal.java:86)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.realAcquire(UnixLikeTTYTerminal.java:87)
        at com.googlecode.lanterna.terminal.ansi.UnixLikeTTYTerminal.<init>(UnixLikeTTYTerminal.java:78)
        at com.googlecode.lanterna.terminal.ansi.CygwinTerminal.<init>(CygwinTerminal.java:59)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createCygwinTerminal(DefaultTerminalFactory.java:416)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createWindowsTerminal(DefaultTerminalFactory.java:411)
        at com.googlecode.lanterna.terminal.DefaultTerminalFactory.createTerminal(DefaultTerminalFactory.java:117)
        at nnrl.lanterna$get_screen.invokeStatic(lanterna.clj:11)
        at nnrl.lanterna$get_screen.invoke(lanterna.clj:8)
        at nnrl.core$_main.invokeStatic(core.clj:119)
        at nnrl.core$_main.doInvoke(core.clj:116)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:377)
        at user$eval149.invokeStatic(form-init4253205981875632234.clj:1)
        at user$eval149.invoke(form-init4253205981875632234.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7052)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        ... 12 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 33 more
`

**Comment by avl42** [comment]
Could you try changing your local lanterna sources and turn "/bin/stty" to
"stty" ?
Would be interesting, if that actually helps, or just delays the error a
tiny bit.

**Comment by CodeFarmer** [comment]
Turns out that Lanterna doesn't have a hardcoded "/bin/tty"; it has this:

```java
    private static String findProgram(String programName) {
        String[] paths = System.getProperty("java.library.path").split(";");
        for(String path : paths) {
            File shBin = new File(path, programName);
            if(shBin.exists()) {
                return shBin.getAbsolutePath();
            }
        }
        return programName;
    }
```

I think I see the problem now. The Cygwin filesystem comes back and says that "/bin/stty" is a file that exists, but the Windows JVM's exec() disagrees. It would be better not to try and find it in java.exec.path in this case at all (or, alternatively, find a way to build a full Windows path) and just let exec() deal with it.

**Comment by CodeFarmer** [comment]
Comment from #335:

> If you run from cmd.exe commandline, then you must use javaw instead of java to launch it, for Lanterna to then open a graphical terminal emulation. (that's a MS Windows peculiarity) If your intention was to really have it run inside the cmd window, then you might want to actively help and try to get the native parts working. pre-requisite for that is adding JNA.

**Comment by CodeFarmer** [comment]
Turns out I was not reading carefully enough. There is another hardcoded "/bin/stty" in UnixLikeTTYTerminal, which CygwinTerminal inherits from. Changing that to a bare "stty" works fine.

**Comment by avl42** [comment]
Well, I do tend to disbelief, that this small change would indeed already make it work.

Reasons: (if any of them can be disproven by a test or fixed, I'd appreciate info)

1.) reports so far were that if stty wasn't directly called from a cygwin-shell then it would only be able to read those settings, but not modify them - in particular it couldn't switch to char mode then.

2.) picking stty from path is a security hazard, as it might accidentally pick up some local stty.exe, instead of cygwin's.  If there's some safer trick to find cygwin's install-path (even from a non-cygwin-application), then a full path should be assembled based on that path.

I appreciate your feedback. We've been waiting for an actual cygwin-user for quite a while...

**Comment by avl42** [comment]
PS:  for quite some time, the only ones stumbling over the /bin/stty problem were users who didn't have cygwin installed, and maybe didn't even know something named cygwin exists. The probability was just ways higher, that any exception in CygwinTerminal would really indicate absence of Cygwin ;-)

Now that someone cygwin knowledgeable (you) is here, support for cygwin once again sees the light at the end of tunnel.

**Comment by mabe02** [comment]
Yeah, cygwin support is still something I'd love to put some work into but I'm out of ideas. Crossing between cygwin-linked applications (stty.exe) and non-cygwin-linked applications (java.exe) just doesn't seem to work. From calling "stty.exe" from outside of the cygwin shell doesn't appear to work either. Furthermore, there isn't any psuedo-terminal device you can manipulate either.
