### ISSUE TITLE
Crash on using Panel.setContent from ActionDialog callback

### ISSUE THREAD

**Issue by dant3** [mabe02/lanterna#155]
I'm trying to update my ui from ActionDialog callback. What I'm doing is:
```scala
val window = new BasicWindow()
window.setComponent(createUi(None))
// ...
val dialog = new ActionDialogBuilder()
dialog.addAction(device.name, toRunnable(() => window.setComponent(createUi(Some(device)))))
dialog.build().showDialog(gui)
// ...
def createUi(device):Panel = Panels.vertical(component1(device), componentWhichMightCallDialogAbove)
//...
def toRunnable(fn: () => Unit):Runnable = new Runnable { override def run() = fn.apply() }
```

But then this Runnable action get's called I'm getting exception:

```
java.lang.NullPointerException
        at com.googlecode.lanterna.gui2.AbstractComponent.toBasePane(AbstractComponent.java:218)
        at com.googlecode.lanterna.gui2.AbstractComponent.toBasePane(AbstractComponent.java:218)
        at com.googlecode.lanterna.gui2.AbstractBasePane.getCursorPosition(AbstractBasePane.java:174)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.getCursorPosition(MultiWindowTextGUI.java:181)
        at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:118)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:144)
        at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:61)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:275)
        at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:164)
        at com.googlecode.lanterna.gui2.dialogs.DialogWindow.showDialog(DialogWindow.java:26)
        at com.github.dant3.catlog.Main$.com$github$dant3$catlog$Main$$showDevicesList(Main.scala:58)
        at com.github.dant3.catlog.Main$$anonfun$createToolbar$1.apply$mcV$sp(Main.scala:44)
        at com.github.dant3.catlog.ui.Toolbar.com$github$dant3$catlog$ui$Toolbar$$handleKeyStroke(Toolbar.scala:20)
        at com.github.dant3.catlog.ui.Toolbar$$anon$1.onUnhandledKeyStroke(Toolbar.scala:16)
        at com.googlecode.lanterna.gui2.AbstractTextGUI.fireUnhandledKeyStroke(AbstractTextGUI.java:154)
        at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:100)
        at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:53)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:275)
        at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:164)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:252)
        at com.github.dant3.catlog.Main$$anonfun$main$1.apply(Main.scala:19)
        at com.github.dant3.catlog.Main$$anonfun$main$1.apply(Main.scala:17) 
        at com.github.dant3.catlog.ui.GUI$.run(GUI.scala:21)
        at com.github.dant3.catlog.Main$.main(Main.scala:17)
        at com.github.dant3.catlog.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
```

You can find complete sources at https://github.com/dant3/catlog/blob/2725bfd14aeb5d1e371096ecd7fb46ee3c0d9c81/src/main/scala/com/github/dant3/catlog/Main.scala#L48

**Comment by mabe02** [comment]
I don't have Scala setup so I can't test with your code, but I think I've fixed it now on master branch if you can build a local 3.0.0-SNAPSHOT. Please let me know!

**Comment by dant3** [comment]
Unfortunately now I see this:
```
[[45;180R[error] (run-main-1) java.io.IOException: Timeout while waiting for terminal size report! Maybe your terminal doesn't support cursor position report, please consider using a custom size querier
java.io.IOException: Timeout while waiting for terminal size report! Maybe your terminal doesn't support cursor position report, please consider using a custom size querier
	at com.googlecode.lanterna.terminal.ansi.StreamBasedTerminal.waitForTerminalSizeReport(StreamBasedTerminal.java:148)
	at com.googlecode.lanterna.terminal.ansi.ANSITerminal.getTerminalSize(ANSITerminal.java:91)
	at com.googlecode.lanterna.terminal.ansi.UnixTerminal.getTerminalSize(UnixTerminal.java:132)
	at com.googlecode.lanterna.screen.TerminalScreen.<init>(TerminalScreen.java:74)
	at com.googlecode.lanterna.screen.TerminalScreen.<init>(TerminalScreen.java:57)
	at com.github.dant3.catlog.ui.GUI$.screen$lzycompute(GUI.scala:12)
	at com.github.dant3.catlog.ui.GUI$.screen(GUI.scala:12)
	at com.github.dant3.catlog.ui.GUI$.run(GUI.scala:20)
	at com.github.dant3.catlog.Main$.main(Main.scala:17)
	at com.github.dant3.catlog.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

 ;180R
```

I left ` ;180R` intentionally - this is what I see falling out after each app run

**Comment by dant3** [comment]
Hm. I'm not sure I understand. I was hoping I could cherry-pick your fix in my local branch & test it, but I don't seem to see any related changes in `master` branch, only ones for JRE 6 compatibility with currently appear to be my culpit. Perhaps you've forgotten to push it?

**Comment by avl42** [comment]
the problem here is, that the emergency fix for the Java 6 build problem left the stty completely unexecuted. This means that the tty wasn't set to cbreak and min 1 mode, and thus the terminal-size query didn't work. 
I've just PR'ed a new fix for the Java 6 build problem, and that should also fix this followup-bug.

**Comment by dant3** [comment]
Yea, I see it. If this is about build I have a second machine with JRE 8 which builds project just fine. I was thinking that fix refered by @mabe02 was for NPE I had with UI, not for build.

**Comment by avl42** [comment]
Viacheslav: I don't quite get the original error.  I don't see a toRunnable, nor a setComponent in the stacktrace...  could you describe in Java terms what your snippet is supposed to do?  Is the "???" just an ellipsis, or is it scala syntax?

**Comment by dant3** [comment]
the `???` is the omitted implementation (it's a predefined function with throws if that matters) since I thought it does not makes sense to mention it here, just that actual `Runnable` is passed.

What happens in terms of java is `toRunnable` creates java `Runnable` which has code passed to `toRunnable` as it's `run()` implementation. `setComponent` is `com.googlecode.lanterna.gui2.Window.setComponent` method call. `createUi` creates a panel with two components inside of it. You can checkout complete sources at link I provided. At the moment of this `setComponent` call I already had previously installed component using `setComponent`.

**Comment by avl42** [comment]
I see you also added some context to your original comment, and it really makes a bit more sense to me now  ;)

Now that I'm a bit less confused, I checked the call stack again and compared it to the code, it seems most likely that some component's parent component has itself a null getParent().

Obviously, something happens between adding a new component to a container, and the container calling the component's onAdded().

Is it possible to single-step Java code within the Lanterna library, from a Scala-project?

**Comment by dant3** [comment]
I'm sorry, I'm not sure I understand this part very well:

> Is it possible to single-step Java code within the Lanterna library, from a Scala-project?

You want a minimal java-based example? Or is this question about java/scala interaction?

**Comment by avl42** [comment]
I meant actually both ;-)
If your Scala-project setup allows you to single-step execution through lanterna's Java code, then please do so to see which component's parent is not set,  otherwise please provide a minimal java class that causes the same error so me or Martin can try to debug it.

**Comment by dant3** [comment]
I tried to debug the problem, but the funny thing is if I run the app with debugger it does not crashes.Also it doesn't looks like to be crashing in 100% of cases then I run it without debugger. This means this is my favourite type of bug - race condition.
I tried to serialize all stuff within TextGUIThread but met a new interesting fact - `AbstractComponent.getTextGUI()` always returns null - as a matter of consequence of that `BasicWindow.setComponent` is actually `AbstractBasePane.setComponent` which sets component to the `AbstractBasePane.ContentHolder` which _always_ has null parent, and so `getParent().getParent().getParent()`  will eventually return `null`... Looks like this has to be fixed in the `BasicWindow`.

**Comment by dant3** [comment]
Looking more in Lanterna looks like it's just that `AbstractBasePane` should be a parent of it's `ContentHolder`

**Comment by avl42** [comment]
With this chain of getParent() ending in a null, then it is surprising how the NPE doesn't always show up...

**Comment by dant3** [comment]
I think it's correct - it should end with null at the top level `Component`, right? perhaps it's just that `null` check is missing?

**Comment by dant3** [comment]
Please disregard the noise before, there is only bug with `getTextGUI` which I fixed locally.

So I finally have the right answer, caught by debugger. At some point the `Panel` has `null` parent. But it's not a `Panel` that resides in `ContentHolder` of the `BasicWindow`.
First screenshot is unfolded tree of `BasicWindow`:
![image](https://cloud.githubusercontent.com/assets/820057/8749715/14456716-2cac-11e5-943e-b1cb35d18b4b.png)

And this is the point of NPE:
![image](https://cloud.githubusercontent.com/assets/820057/8749745/3321f73a-2cac-11e5-9f8b-7edbaa6e3e1f.png)

As I thought it some sort of race inside of Lanterna.

**Comment by avl42** [comment]
I see a Panel with an id 2180 as "this" in the second pic, but not in the first one. I only see a ContentHolder with id 2181 up there in the first one.

Did you see (during stepping through it) where something was added to a container, but not "parent'ed?
Could it be that (of your original stacktrace) it is one of these methods on the stack
           at com.github.dant3.catlog.Main$$anonfun$main$1.apply(Main.scala:19)
           at com.github.dant3.catlog.Main$$anonfun$main$1.apply(Main.scala:17) 
that would eventually later do the parent-wiring? (just idle guessing)

Is it possible to simplify your initial example to use Buttons instead of "component1(device)" and "componentWhichMightCallDialogAbove", and then still reproduce the bug?

**Comment by dant3** [comment]
I've added a testcase which reproduces same issue without custom components and written in Java ;)

**Comment by dant3** [comment]
@avl42  to answer your question - I'm not changing any parenting explicitly, besides using `AbstractBasePane.setComponent` method call, and this call is not within stacktrace. The `Panel` you see as `this` on a second screenshot appears to be the old `setComponent`-ed `Panel` I setted up before calling the `Dialog`.

**Comment by avl42** [comment]
Ok, I just fetched your Issue155 branch, and tried it, and it crashes for me, too :-)

After some stepping through the code, my diagnose is, that Window.setComponent replaces the component, but doesn't notice that the `focusedInteractable` is a grand{*}child of the old component. All goes fine, until it asks the old(!) `focusedInteractable` about location of the cursor, which it tries to propagate up the hierarchy, until it hits null from the removed old Panel.

I think it should be safe to just reset the `focusedInteractable` to null, when an old component is removed. After all there should have been only that one component, and the focused one must have been the old component or a child of that...

**Comment by avl42** [comment]
I just opened a PR for dant3's Issue155 branch.
Please check it (especially for unlikely but possible newly introduced Java6-build problems)

**Comment by mabe02** [comment]
I've merged these, and yes, we should probably set focusedInteractable to null whenever the component of the Window/BasePane is changed and the focused component was set.

**Comment by mabe02** [comment]
Done, I've updated master with code to reset focusedInteractable whenever the main component of AbstractBasePane changes

**Comment by avl42** [comment]
please also have a look at the commit that I PR'ed to dant3:

  https://github.com/avl42/lanterna/commit/63991beae50ae54d73a106c479123fa2bab1b285

the point is to override removeComponent, to also catch the case where current component is just removed without setting a new one. this also gets invoked from super.setComponent, thus no need to change setComponent itself.

**Comment by mabe02** [comment]
Yes, we need that one too. I'll see if I can pull it in.

**Comment by mabe02** [comment]
Ok, merged now. Viacheslav, are you able to test the latest snapshot and see if we can close this issue?

**Comment by dant3** [comment]
Just tested using SNAPSHOT of 470c4da299 and it works just fine for me.
