### ISSUE TITLE
IndexOutOfBoundsException when creating a new BasicWindow

### ISSUE THREAD

**Issue by jcfrei** [mabe02/lanterna#164]
I'm creating and adding a new BasicWindow and occasionally (but rarely) get the following error. I've checked my own code several times and cannot really find a cause for the error. Could it come from the lanterna code - maybe some racing condition?

The error always gets thrown upon the creation of a new BasicWindow, like this:
    ````multiWindowTextGUI.addWindow(new LanternaManageRunsWindow());````

btw. ````LanternaManageRunsWindow```` extends ````BasicWindow````

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.googlecode.lanterna.gui2.InteractableLookupMap.getDisqualifiedInteractables(InteractableLookupMap.java:228)
        at com.googlecode.lanterna.gui2.InteractableLookupMap.findNextLeftOrRight(InteractableLookupMap.java:166)
        at com.googlecode.lanterna.gui2.InteractableLookupMap.findNextLeft(InteractableLookupMap.java:134)
        at com.googlecode.lanterna.gui2.AbstractBasePane.handleInput(AbstractBasePane.java:119)
        at com.googlecode.lanterna.gui2.AbstractWindow.handleInput(AbstractWindow.java:101)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.handleInput(MultiWindowTextGUI.java:224)
        at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:98)
        at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:53)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:102)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$0(SeparateTextGUIThread.java:88)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:43)

**Comment by avl42** [comment]
This seems to be a deterministic problem (in Lanterna): when a new Window happens to get keyboard-traversed before having first been drawn. InteractableLookupMap has an array that contains zeros right after construction, while after a call to reset() (which happens only from within draw())  it is filled with values of -1. It's the zeros that hurt.

I don't know how it happens in your class LanternaManageRunsWindow, that it gets to handle a keystroke before even being drawn, and I don't know why this apparently hasn't happened anywhere else before, but I think it should be fixed in Lanterna, anyway.

I'm going to prepare a patch...

**Comment by jcfrei** [comment]
Thanks a lot for the forthcoming handling of the patches! I could successfully replicate the error in a matter that makes it seem consistent with your explanation. The button which opens the window is the last one in a horizontal pane. When I spam the right arrow and then open the window I can reliably reproduce the error. In my case it can apparently handle a keystroke before it has appeared because the GUI is rather slow - I assume because I update a textbox quite frequently in the background.

**Comment by avl42** [comment]
I added it to an already open PR.

The "bad news" is, that Martin seems to be busy sometimes, so it might take some time till this is merged into mabe02/lanterna.

The "good news" is, that the fix is pretty simple, and you can view it from the "referenced"-link and probably easily apply it to your local checkout of Lanterna for a first test on the spot. :-)

**Comment by mabe02** [comment]
Yeah, had another one of those weeks where I barely see anything outside my office, but I'm back merging stuff today!
