### ISSUE TITLE
DefaultTextBoxRenderer: java.lang.NullPointerException

### ISSUE THREAD

**Issue by jcfrei** [mabe02/lanterna#179]
I randomly get this error. I believe it occurs when the size of the terminal changes (when I connect to the server with another computer) and when the application isn't displayed (ie. when I use GNU screen).

It's probably due to this line:

drawTextArea(graphics.newTextGraphics(TerminalPosition.TOP_LEFT_CORNER, realTextArea), component);

but I'm not sure

```
java.lang.NullPointerException
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawTextArea(TextBox.java:596)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:530)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:459)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:178)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:153)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:146)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:131)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:178)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:153)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:146)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:131)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:178)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:153)
     at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:277)
     at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:261)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:178)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:153)
     at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:59)
     at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:98)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:189)
     at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:117)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:159)
     at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:61)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:102)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:32)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:43)
```

**Comment by avl42** [comment]
I'd rather suspect line TextBox.java:596 ... apparently "line" can be null there, so changing it to 

                if(line != null && line.length() > viewTopLeft.getColumn()) {

should fix at least this part.

I'm not yet sure about how to reproduce it. Is it only in your own program, or can you reproduce it also with one of lanterna's test programs?

**Comment by jcfrei** [comment]
I'm trying it in my application right now. Tests might take a while longer.

**Comment by mabe02** [comment]
Yeah, that's definitely weird, I'd rather expect an IndexOutOfBoundsException at that point. But resizing windows quickly tends to uncover weird issues so I'm not all that surprised.

**Comment by jcfrei** [comment]
So the previous error didnt resurface again, however I received a new one:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 9
     at java.util.ArrayList.rangeCheck(ArrayList.java:635)
     at java.util.ArrayList.get(ArrayList.java:411)
     at com.googlecode.lanterna.gui2.TextBox.getLine(TextBox.java:294)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawTextArea(TextBox.java:621)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:575)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:502)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:146)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:131)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:146)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:131)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
     at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:277)
     at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:261)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
     at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:59)
     at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:98)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:189)
     at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:117)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:159)
     at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:66)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:102)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:32)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:43)

```

**Comment by mabe02** [comment]
Ok, I've added some extra synchronization to the TextBox class, I don't think it's the problem here but if you recompile latest lanterna, can you try again?

**Comment by jcfrei** [comment]
Thanks! I'm running the new version now and will report back.

**Comment by jcfrei** [comment]
After some time the following error now appeared (using the latest build):

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 10
     at java.lang.String.charAt(String.java:658)
     at com.googlecode.lanterna.CJKUtils.getColumnIndex(CJKUtils.java:93)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawTextArea(TextBox.java:637)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:587)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:514)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:146)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:131)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:146)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:131)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
     at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:277)
     at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:261)
     at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
     at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:59)
     at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:97)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:189)
     at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:117)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:159)
     at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:66)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:102)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:32)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:43)

```

**Comment by avl42** [comment]
The bug appears to be in TextBox.java:634  (your 637 - have you added debugging code locally?)
where it assumes that the caret's column-position is never beyond the end of that line.

On the other hand, maybe CJKUtils.getColumnIndex(...) should just be made robust against such situations...

**Comment by jcfrei** [comment]
That's right I've added the following line, apparently without success:

```
....
 if(!component.isReadOnly()) {
                //Adjust the view if necessary
                TerminalPosition caretPosition = component.getCaretPosition();
                if(caretPosition.getRow() >= component.lines.size()){
                        return;
                }
                String caretLine = component.getLine(caretPosition.getRow());
               ....

```

**Comment by avl42** [comment]
You probably want to check:

    if(caretPosition.**getColumn**() >= component.lines.size()){ ...

instead :-)

**Comment by avl42** [comment]
oups... not in that exact line...

caretPosition.getColumn() needs to be checked against caretLine.lengh()
after declaration&initialization of caretLine...

**Comment by mabe02** [comment]
Ok, I've pushed a new change that should prevent the exception but I'm not sure if it fixes the underlying reason. Can you try again with the latest source and let us know how it goes? Also, look for oddities with text box and how the caret moves around.

**Comment by jcfrei** [comment]
Ok, thanks! I've added the new code and will update later.

**Comment by jcfrei** [comment]
After some (not very rigorous) testing it seems to me that the issue is resolved.

**Comment by mabe02** [comment]
Thanks!
