### ISSUE TITLE
Border Layout crashes with the auto resize layout and doesn't resize properly.

### ISSUE THREAD

**Issue by lyze237** [mabe02/lanterna#190]
Initialization of the GUI: http://imgur.com/EHiVgLz

        DefaultTerminalFactory factory = new DefaultTerminalFactory();
        factory.setInitialTerminalSize(new TerminalSize(150,50));
        factory.setSwingTerminalFrameTitle(name);
        terminal = factory.createTerminal();
        screen = new TerminalScreen(terminal);
        screen.startScreen();

        Panel panel = new Panel();
        panel.setLayoutManager(new BorderLayout());

        channels = new ActionListBox();
        channels.setLayoutData(BorderLayout.Location.LEFT);
        panel.addComponent(channels.withBorder(Borders.singleLine("Channels")));

        log = new TextBox("", TextBox.Style.MULTI_LINE);
        log.setReadOnly(true);
        log.setLayoutData(BorderLayout.Location.CENTER);
        panel.addComponent(log.withBorder(Borders.singleLine("Log")));

        Panel options = new Panel();
        options.setLayoutData(BorderLayout.Location.BOTTOM);

        options.withBorder(Borders.singleLine("Send Message"));

        options.setLayoutManager(new BorderLayout());

        input = new TextBox("Message", TextBox.Style.SINGLE_LINE);
        input.setLayoutData(BorderLayout.Location.CENTER);
        options.addComponent(input);

        send = new Button("Send", () -> {
            picarto.sendMessageThreadSafe(channels.getSelectedItem().toString(), input.getText());
            input.setText("");
        });
        send.setLayoutData(BorderLayout.Location.RIGHT);
        options.addComponent(send);

        panel.addComponent(options.withBorder(Borders.singleLine("Send Message")));

        window = new BasicWindow();
        window.setComponent(panel.withBorder(Borders.doubleLine("DarkOwlBot")));

        window.setHints(Arrays.asList(Window.Hint.EXPANDED, Window.Hint.FIT_TERMINAL_WINDOW));

Running the Gui (via a different thread):

        MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
        gui.addWindowAndWait(window);

Behaviour: https://youtu.be/-UxVciU7eOE
* On resize: Only panel gets resized
* Text area will be resized when I press a button
* Bottom Panel (options) won't get resized

Crashlog:

    Exception in thread "Thread-3" java.lang.NullPointerException
	at com.googlecode.lanterna.gui2.Borders.joinLinesWithFrame(Borders.java:337)
	at com.googlecode.lanterna.gui2.Borders$AbstractBorderRenderer.drawComponent(Borders.java:202)
	at com.googlecode.lanterna.gui2.Borders$AbstractBorderRenderer.drawComponent(Borders.java:111)
	at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:146)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:131)
	at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
	at com.googlecode.lanterna.gui2.Borders$AbstractBorderRenderer.drawComponent(Borders.java:199)
	at com.googlecode.lanterna.gui2.Borders$AbstractBorderRenderer.drawComponent(Borders.java:111)
	at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:277)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:261)
	at com.googlecode.lanterna.gui2.AbstractComponent.drawComponent(AbstractComponent.java:187)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:162)
	at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:59)
	at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:97)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:190)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:117)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:160)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:66)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:316)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:185)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:283)
	at at.lyze.Logger.ConsoleLogWindow.display(ConsoleLogWindow.java:84)
	at at.lyze.Logger.CustomLoggerFactory.lambda$initialize$3(CustomLoggerFactory.java:73)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mabe02** [comment]
Okay, I think the crash is fixed now in the latest version. Looking into why the elements are not resizing properly...

**Comment by mabe02** [comment]
Yeah, looks like the BorderLayout isn't refreshing correctly

**Comment by mabe02** [comment]
OK, I think I got it now. Please try with the latest repository version, if you can.

**Comment by mabe02** [comment]
Assuming this is now fixed, please let me know if it is not
