### ISSUE TITLE
java.lang.IllegalArgumentException: null label to a button is not allowed

### ISSUE THREAD

**Issue by jcfrei** [mabe02/lanterna#195]
After an update to the latest commit I get the following error:

```
java.lang.IllegalArgumentException: null label to a button is not allowed
     at com.googlecode.lanterna.gui2.Button.setLabel(Button.java:84)
     at com.googlecode.lanterna.gui2.Button.<init>(Button.java:56)
     at com.googlecode.lanterna.gui2.dialogs.MessageDialog.<init>(MessageDialog.java:29)
     at com.googlecode.lanterna.gui2.dialogs.MessageDialogBuilder.build(MessageDialogBuilder.java:30)
     at application.client.gui.LanternaCommandWindow$6.run(LanternaCommandWindow.java:98)
     at com.googlecode.lanterna.gui2.Button.handleKeyStroke(Button.java:72)
     at com.googlecode.lanterna.gui2.AbstractInteractableComponent.handleInput(AbstractInteractableComponent.java:115)
     at com.googlecode.lanterna.gui2.AbstractBasePane.handleInput(AbstractBasePane.java:87)
     at com.googlecode.lanterna.gui2.AbstractWindow.handleInput(AbstractWindow.java:127)
     at application.client.gui.LanternaCommandWindow.handleInput(LanternaCommandWindow.java:141)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.handleInput(MultiWindowTextGUI.java:317)
     at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:115)
     at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:58)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:114)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:44)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:55)
```

I created the dialog window like below. Which should be ok according to https://github.com/mabe02/lanterna/blob/5c85c474dd90be360943b4d1b0e145c69101f8ca/docs/examples/gui/message_dialogs.md
```
horizontalPanel.addComponent(new Button("Quit", new Runnable() {
			@Override
			public void run() {
				final MessageDialog messageDialog= new MessageDialogBuilder().setText("Do you really want to quit?").
						setTitle("Quit?").addButton(MessageDialogButton.Yes).addButton(MessageDialogButton.No).
						build();
				MessageDialogButton result = messageDialog.showDialog(lwm.returnWindowBasedTextGUI());
				if(result == MessageDialogButton.Yes) {
					lwm.stopApplication();
				} else {
				// should close by itself?
				}
			}
		}));
		basePanel.addComponent(horizontalPanel);
```

**Comment by avl42** [comment]
Among the latest changes were also ressource-bundles for non-english languages. 
Is it possible that you only deploy the compiled .class files, but not the ressources?

**Comment by avl42** [comment]
PS: Note, you also need these ressource-bundles for English language, not just for others.

**Comment by jcfrei** [comment]
thanks a lot for clearing that up. the resources were indeed missing from the building path.

**Comment by mabe02** [comment]
I suppose I can close this?
