### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jcfrei** [mabe02/lanterna#202]
Stumbled upon this one recently (happend only once so far). I couldn't really determine what triggered it:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 21
     at java.lang.String.charAt(String.java:658)
     at com.googlecode.lanterna.TerminalTextUtils.getColumnIndex(TerminalTextUtils.java:111)
     at com.googlecode.lanterna.gui2.TextBox.handleKeyStroke(TextBox.java:483)
     at com.googlecode.lanterna.gui2.AbstractInteractableComponent.handleInput(AbstractInteractableComponent.java:115)
     at com.googlecode.lanterna.gui2.AbstractBasePane.handleInput(AbstractBasePane.java:87)
     at com.googlecode.lanterna.gui2.AbstractWindow.handleInput(AbstractWindow.java:127)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.handleInput(MultiWindowTextGUI.java:317)
     at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:115)
     at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:58)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:114)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:44)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:55)

```

**Comment by mabe02** [comment]
Have you been able to reproduce it or was it just random?

**Comment by jcfrei** [comment]
So far it has only occurred once, so I would say random.

**Comment by avl42** [comment]
@jcfrei  it would be good if you could remember some details of that one case:

1. Did the TextBox contain "double wide" characters?
2. Where you moving the cursor horizontally or vertically?
3. Did the text in the TextBox eventually get updated in the background (or was it static)?

Things like these might help pinpoint the problem, even while you cannot yet reproduce it...

**Comment by avl42** [comment]
When I wrote last comment, I didn't yet get to check the stacktrace against lanterna source -- question 2 is answered already from the stack: the ArrowUp key was typed.

For some reason, the caretPosition points behind the last character of old line.

From checking the other cases of that switch, such a situation could result from PageUp/PageDown keys, which only update the row, but not check the column against the target line.

**Comment by jcfrei** [comment]
1)  It didn't contain double wide characters
2) Yes, I remember moving vertically - most likely with PgUp/PgDown keys.
3) No, everything remained static after that

**Comment by mabe02** [comment]
I've been able to reproduce it, should be easy to fix

**Comment by mabe02** [comment]
OK, fix should be available now on latest master
