### ISSUE TITLE
Table not working with 3.0.0-beta2

### ISSUE THREAD

**Issue by nikiroo** [mabe02/lanterna#212]
Table not working with 3.0.0-beta2

(In my case I simply used another container, but I suppose you'd like to know the Table class is broken --- it seems it is just the custom "HEADER" style which is not defined, but I have no idea where it should be defined; should be easy to fix?)

in DefaultTableHeaderRenderer.java :
`		textGUIGraphics.applyThemeStyle(textGUIGraphics.getThemeDefinition(Table.class).getCustom("HEADER"));`
This call will return NULL, which will be passed lower down and crash the application.

Small code to reproduce:
Simply follow the tuutorial at https://github.com/mabe02/lanterna/blob/master/docs/examples/gui/tables.md
I.E.:
```
		final Table<String> table = new Table<String>("Column 1", "Column 2",
				"Column 3");
		table.getTableModel().addRow("1", "2", "3");
		table.setSelectAction(new Runnable() {
			@Override
			public void run() {
				List<String> data = table.getTableModel().getRow(
						table.getSelectedRow());
				for (int i = 0; i < data.size(); i++) {
					System.out.println(data.get(i));
				}
			}
		});

		Window win = new BasicWindow();
		win.setComponent(table);
		
		DefaultTerminalFactory factory = new DefaultTerminalFactory();
			Terminal terminal = factory.createTerminal();

		Screen screen = new TerminalScreen(terminal);
		screen.startScreen();

		// Create gui and start gui
		MultiWindowTextGUI gui = new MultiWindowTextGUI(screen,
				new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
		gui.addWindowAndWait(win);

		screen.stopScreen();
```

Stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at com.googlecode.lanterna.graphics.ImmutableThemedTextGraphics.applyThemeStyle(ImmutableThemedTextGraphics.java:62)
	at com.googlecode.lanterna.gui2.TextGUIGraphics.applyThemeStyle(TextGUIGraphics.java:70)
	at com.googlecode.lanterna.gui2.table.DefaultTableHeaderRenderer.drawHeader(DefaultTableHeaderRenderer.java:25)
	at com.googlecode.lanterna.gui2.table.DefaultTableRenderer.drawHeader(DefaultTableRenderer.java:253)
	at com.googlecode.lanterna.gui2.table.DefaultTableRenderer.drawComponent(DefaultTableRenderer.java:235)
	at com.googlecode.lanterna.gui2.table.DefaultTableRenderer.drawComponent(DefaultTableRenderer.java:1)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:205)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:270)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:1)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:205)
	at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:64)
	at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:126)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:259)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:134)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:220)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:66)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:391)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:227)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:358)
```

**Comment by mabe02** [comment]
Thank you for the bug report, I'll take a look at this tonight

**Comment by mabe02** [comment]
Wasn't able to reproduce this, but I did alter the theme system slightly so it avoids the NPE you had. Please check the Issue212 class in the test directory, if you run it, does it trigger the bug?

**Comment by nikiroo** [comment]
I confirm. Downloading the current master tree and executing Issue212 does work correctly.
Thanks.
