### ISSUE TITLE
Crash (not freeze) in some cases when handling input (method handleInput())

### ISSUE THREAD

**Issue by nikiroo** [mabe02/lanterna#214]
Crash (not freeze) in some cases when handling input (method handleInput())

The crash points to InteractableLookupMap.java
I don't really know how to reproduce it, but it happens once in a while.
I'll update you if I find more usage information.
Still, the crash happens at
```
        startPosition = interactable.toBasePane(startPosition);
        Set<Interactable> disqualified = getDisqualifiedInteractables(startPosition, true);
```
It seems from toBasePane javadoc that the method can return NULL (it indeed does in this case), but getDisqualifiedInteractables causes a NPE if you pass it NULL.

Stack trace, in case it helps:
```
tail: /tmp/err: file truncated
Exception in thread "main" java.lang.NullPointerException
	at com.googlecode.lanterna.gui2.InteractableLookupMap.getDisqualifiedInteractables(InteractableLookupMap.java:252)
	at com.googlecode.lanterna.gui2.InteractableLookupMap.findNextUpOrDown(InteractableLookupMap.java:139)
	at com.googlecode.lanterna.gui2.InteractableLookupMap.findNextUp(InteractableLookupMap.java:101)
	at com.googlecode.lanterna.gui2.AbstractBasePane.handleInput(AbstractBasePane.java:141)
	at com.googlecode.lanterna.gui2.AbstractWindow.handleInput(AbstractWindow.java:131)
	at be.nikiroo.jvcard.tui.MainWindow.handleInput(MainWindow.java:539)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.handleInput(MultiWindowTextGUI.java:321)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:115)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:58)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:391)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:227)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:358)
	at be.nikiroo.jvcard.tui.TuiLauncher.start(TuiLauncher.java:47)
	at be.nikiroo.jvcard.tui.Main.main(Main.java:54)
```

In my code, near the mentioned line, I basically handle the input then do:
```
		if (!handled)
			handled = super.handleInput(key);

		return handled;
```

While handling the input, I do indeed modify the GUI, including adding new elements.
Maybe that's one of the reason it crashes?

Note that the method does not say one cannot modify the GUI while handling input, and it seems kind of useful, too. But maybe I'm wrong there?

Still, it only happens sporadically, so I guess it is indeed a bug?

**Comment by avl42** [comment]
may be a trivial question, but when you react on a keystroke to change structure or layout of components, then do you make sure to "declare" the action as handled?

**Comment by avl42** [comment]
ps: i mean like returning true from your overridden handle... method.

**Comment by nikiroo** [comment]
Actually, no.
I reset a message pane at each keystroke, without "handling" the action from the program logic perspective.
```
    panel.removeAllComponents();
```
(panel which may contain a Label in a LinearLayout with option Alignment.Center before I clean it.)

Could it be a problem?

**Comment by avl42** [comment]
it's worth a try...

**Comment by avl42** [comment]
(that previous message was a short reply from phone)

Whenever you react to a keystroke, then you should definitely return true, and this will stop lanterna from trying itself to do something with it (which was the point where it failed).
 
If you change the structure (panel.removeAllComponents();) and still let lanterna do it's own stuff, then it will assume the original state of gui and that breaks.

I can't say for sure that there couldn't be a way to make lanterna robust against changed structure, but that might have a series of consequences that I cannot fully predict.

**Comment by nikiroo** [comment]
Ok, that would explains the problem.
I will change the way I handle my messages.

By the way, I saw nothing about that in the jDoc nor the doc I read (though I didn't skim all the documentation); do you think you could add this information in the jdoc of the return parameter of handleInput()?

Thanks!

On the same note, is it safe to modify the GUI while overriding draw(TextGUIGraphics)?
Or should I also change that or risk having the same kind of issues happening there?

**Comment by avl42** [comment]
I'd rather not do that (modify components in draw) at all. 
In contrast, it is ok to modify the gui from handleKeyStroke, as long as you return true then.

**Comment by mabe02** [comment]
Yes, you should always mark that the event was processed when you override handleInput. I've added some code to try to avoid NPEs when the interactable has been removed from the basepane (Window) in the input handling, hopefully this particular case will go away.
