### ISSUE TITLE
Test case failing

### ISSUE THREAD

**Issue by boekhold** [mabe02/lanterna#227]
SimpleWindowManagerTest is failing in the following tests:
- Full-screen window
- Undecorated + Full-screen window
- Expanded window
- Undecorated + Expanded window

**Comment by avl42** [comment]
The Full- and Expanded tests download a copy of the GPL from http://www.gnu.org/licenses/gpl.txt just for the purpose of something to display in those windows.

My guess is, that your test machine is offline, so downloading that URL fails...

**Comment by boekhold** [comment]
Umm, no, I'm very much online :) I'm replying to this issue from the same machine. I'm getting a NullPointerException in:

```java
java.lang.NullPointerException
	at com.googlecode.lanterna.gui2.AbstractComponent.getRenderer(AbstractComponent.java:100)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
	at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:721)
	at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:613)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:180)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:165)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:270)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:254)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
	at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:64)
	at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:127)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:258)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:120)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:219)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:83)
	at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:114)
	at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:44)
	at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:55)
```

**Comment by avl42** [comment]
Seems like that was introduced with latest updates about theme-ing...  I haven't pulled those, yet, and it didn't fail here.

**Comment by mabe02** [comment]
Yeah, probably a regression, I'll take a look

**Comment by mabe02** [comment]
OK, I believe it's fixed now

**Comment by avl42** [comment]
@boekhold could you give feedback and eventually close it?

**Comment by mabe02** [comment]
Stale, closing...
