### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by jcfrei** [mabe02/lanterna#228]
```
java.lang.NullPointerException
     at com.googlecode.lanterna.gui2.AbstractComponent.getRenderer(AbstractComponent.java:100)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:729)
     at com.googlecode.lanterna.gui2.TextBox$DefaultTextBoxRenderer.drawComponent(TextBox.java:613)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:180)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:165)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:180)
     at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:165)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
     at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:270)
     at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:254)
     at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:173)
     at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:64)
     at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:127)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:258)
     at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:120)
     at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:219)
     at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:83)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:114)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:44)
     at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:55)


```

using the newest commit

**Comment by mabe02** [comment]
Yes, this is a regression, already reported in #227 
I'll close this as a duplicate
