### ISSUE TITLE
Resize issue with Gnome Terminal

### ISSUE THREAD

**Issue by olivierlemasle** [mabe02/lanterna#229]
Hi,

I'm having issues with Lanterna 3 on Gnome terminal, when I resize the terminal window. This does not happen always, but typically after 3 or 4 changes of terminal size.

Error:

```
Exception in thread "SIGWINCH handler" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy0.handle(Unknown Source)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Timeout while waiting for terminal size report! Your terminal may have refused to go into cbreak mode.
	at com.googlecode.lanterna.terminal.ansi.StreamBasedTerminal.waitForTerminalSizeReport(StreamBasedTerminal.java:163)
	at com.googlecode.lanterna.terminal.ansi.ANSITerminal.getTerminalSize(ANSITerminal.java:92)
	at com.googlecode.lanterna.terminal.ansi.UnixTerminal.getTerminalSize(UnixTerminal.java:140)
	at com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal$1.invoke(UnixLikeTerminal.java:146)
	... 3 more
```

I'm using lantena 3.0.0-beta2.
My terminal is Gnome Terminal 3.18.3, on Fedora 23.

My test case:

```java
import java.io.IOException;
import java.util.Arrays;

import com.googlecode.lanterna.TextColor;
import com.googlecode.lanterna.gui2.BasicWindow;
import com.googlecode.lanterna.gui2.DefaultWindowManager;
import com.googlecode.lanterna.gui2.EmptySpace;
import com.googlecode.lanterna.gui2.Label;
import com.googlecode.lanterna.gui2.MultiWindowTextGUI;
import com.googlecode.lanterna.gui2.Panel;
import com.googlecode.lanterna.gui2.Window;
import com.googlecode.lanterna.screen.Screen;
import com.googlecode.lanterna.screen.TerminalScreen;
import com.googlecode.lanterna.terminal.DefaultTerminalFactory;
import com.googlecode.lanterna.terminal.Terminal;

public class Main {

  public void run() throws IOException {
    final Terminal terminal = new DefaultTerminalFactory().createTerminal();
    final Screen screen = new TerminalScreen(terminal);
    screen.startScreen();

    final Panel panel = new Panel();
    new Label("This is a test").addTo(panel);

    final BasicWindow window = new BasicWindow();
    window.setHints(Arrays.asList(Window.Hint.CENTERED));
    window.setComponent(panel);

    final MultiWindowTextGUI gui = new MultiWindowTextGUI(screen,
        new DefaultWindowManager(),
        new EmptySpace(TextColor.ANSI.BLUE));
    gui.addWindowAndWait(window);
    screen.stopScreen();
  }

  public static void main(final String[] args) throws IOException {
    (new Main()).run();
  }

}
```

At first, it's running correctly:

![ok](https://cloud.githubusercontent.com/assets/628140/14403129/f8ea8b32-fe4b-11e5-9947-b66efce2961b.png)

I resize the terminal window multiple times (usually between 2 or 5 times), and then I get the error:

![nok](https://cloud.githubusercontent.com/assets/628140/14403133/23c1ea12-fe4c-11e5-8964-2af1d1a98f4f.png)

If I restart the window again, I sometimes get the normal display again, then the error again, etc.

It looks like #61, but that issue was with Lanterna 2.

**Comment by mabe02** [comment]
There's been some work on the I/O layer since the last beta release, I'll do another one shortly and let's see if that fixes it

**Comment by olivierlemasle** [comment]
You're right; I've running the same test case with latest Lanterna built from master branch, and the bug is fixed; thanks!
I'm looking forward to using the next beta release!
