### ISSUE TITLE
java.lang.IndexOutOfBoundsException on empty table

### ISSUE THREAD

**Issue by lonely-lockley** [mabe02/lanterna#235]
Hi there!
  I get this exception when adding an empty table to a window. 
Here is the full stack trace:
`
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.googlecode.lanterna.gui2.table.DefaultTableRenderer.drawHeader(DefaultTableRenderer.java:252)
	at com.googlecode.lanterna.gui2.table.DefaultTableRenderer.drawComponent(DefaultTableRenderer.java:235)
	at com.googlecode.lanterna.gui2.table.DefaultTableRenderer.drawComponent(DefaultTableRenderer.java:16)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:205)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:180)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:165)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:205)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:270)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:254)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:205)
	at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:64)
	at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:126)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:259)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:134)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:220)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:66)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:391)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:227)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:358)
	at just.forr.fun.Test.main(Test.java:62)
`

Here is the code leading to a problem:
```Java
        Terminal terminal = new DefaultTerminalFactory().createTerminal();
        Screen screen = new TerminalScreen(terminal);
        screen.startScreen();

        // Create panel to hold components
        Panel panel = new Panel();
        panel.setLayoutManager(new GridLayout(2));

        final Table<String> table = new Table<>("Column 1", "Column 2");
        // enable this to avoid crash
//        table.getTableModel().addRow("", "");

        panel.addComponent(new EmptySpace(new TerminalSize(0,0))); // Empty space underneath labels
        panel.addComponent(table);
```
Lanterna version: 3.0.0-beta2

**Comment by jslater89** [comment]
@mabe02 I submitted a pull request #238 to fix this, and another Table issue I came across in testing.

**Comment by mabe02** [comment]
Looks good, that's now merged. Thank you!
