### ISSUE TITLE
No X11 DISPLAY variable was set, but this program performed an operation which requires it

### ISSUE THREAD

**Issue by jcfrei** [mabe02/lanterna#236]
Shouldn't lanterna run headless? Is there a run parameter I need to set when starting it via an ssh session? Or have some constructors changed?

```
Exception in thread "Thread-18" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
       at sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(HeadlessGraphicsEnvironment.java:72)
       at com.googlecode.lanterna.terminal.swing.AWTTerminalFontConfiguration.getFontSize(AWTTerminalFontConfiguration.java:109)
       at com.googlecode.lanterna.terminal.swing.AWTTerminalFontConfiguration.getDefaultLinuxFonts(AWTTerminalFontConfiguration.java:79)
       at com.googlecode.lanterna.terminal.swing.AWTTerminalFontConfiguration.selectDefaultFont(AWTTerminalFontConfiguration.java:141)
       at com.googlecode.lanterna.terminal.swing.AWTTerminalFontConfiguration.getDefault(AWTTerminalFontConfiguration.java:154)
       at com.xxxxx.client.gui.MyTerminalFactory.<init>(MyTerminalFactory.java:94)
       at com.xxxxx.client.gui.MyTerminalFactory.<init>(MyTerminalFactory.java:73)
       at com.xxxxx.client.gui.LanternaWindowManager.run(LanternaWindowManager.java:158)
```

The relevant lines in MyTerminalFactory:

```
public MyTerminalFactory(OutputStream outputStream, InputStream inputStream, Charset charset) {
        this.outputStream = outputStream;
        this.inputStream = inputStream;
        this.charset = charset;
        
        this.suppressSwingTerminalFrame = false;
        this.autoOpenSwingTerminalFrame = true;
        this.title = "SwingTerminalFrame";
        this.autoCloseTrigger = TerminalEmulatorAutoCloseTrigger.CloseOnExitPrivateMode;
        this.colorConfiguration = TerminalEmulatorColorConfiguration.getDefault();
        this.deviceConfiguration = TerminalEmulatorDeviceConfiguration.getDefault();
        this.fontConfiguration = AWTTerminalFontConfiguration.getDefault(); // line 94
        this.mouseCaptureMode = null;
    }
```

**Comment by mabe02** [comment]
It does run in headless mode, but when you call `AWTTerminalFontConfiguration.getDefault();`, as you can see in the stack trace, it eventually ends up in the AWT code that isn't headless. Try not to call `AWTTerminalFontConfiguration` (or any of the other terminal customization classes) unless you know you are going to create a AWT/Swing-based terminal.
