### ISSUE TITLE
Exception when resizing

### ISSUE THREAD

**Issue by EnderCrypt** [mabe02/lanterna#254]
terminal = new DefaultTerminalFactory().createTerminal();
screen = new TerminalScreen(terminal);

working with the screen object

when resizing the Terminal window to less than 1 row in size, you get this exception (the first occurs once, and the second exception keeps getting thrown, even if you resize it back to a legal size)

`Exception in thread "Timer-0" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.googlecode.lanterna.graphics.BasicTextImage.copyTo(BasicTextImage.java:174)
	at com.googlecode.lanterna.screen.ScreenBuffer.copyTo(ScreenBuffer.java:117)
	at com.googlecode.lanterna.screen.TerminalScreen.refresh(TerminalScreen.java:149)
	at com.googlecode.lanterna.screen.AbstractScreen.refresh(AbstractScreen.java:191)
	at com.github.endercrypt.Main$1.run(Main.java:42)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Illegal argument to TextBuffer.getCharacter(..), lineNumber = -1, columnIndex = 0
	at com.googlecode.lanterna.terminal.virtual.TextBuffer.getCharacter(TextBuffer.java:104)
	at com.googlecode.lanterna.terminal.virtual.DefaultVirtualTerminal.getBufferCharacter(DefaultVirtualTerminal.java:304)
	at com.googlecode.lanterna.terminal.virtual.DefaultVirtualTerminal.getCharacter(DefaultVirtualTerminal.java:299)
	at com.googlecode.lanterna.terminal.virtual.DefaultVirtualTerminal.getCharacter(DefaultVirtualTerminal.java:291)
	at com.googlecode.lanterna.terminal.swing.GraphicalTerminalImplementation.buildDirtyCellsLookupTable(GraphicalTerminalImplementation.java:472)
	at com.googlecode.lanterna.terminal.swing.GraphicalTerminalImplementation.updateBackBuffer(GraphicalTerminalImplementation.java:332)
	at com.googlecode.lanterna.terminal.swing.GraphicalTerminalImplementation.paintComponent(GraphicalTerminalImplementation.java:273)
	at com.googlecode.lanterna.terminal.swing.SwingTerminal.paintComponent(SwingTerminal.java:183)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5217)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3912)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

is there maybe any way to prevent set a minimum size of a Terminal (atleast untill this is fixed or disable resizing or something?)

**Comment by mabe02** [comment]
Hmm, I thought this was fixed already...? Which version are you on?

**Comment by EnderCrypt** [comment]
hello :) i decided to use maven, so im using the one written on the main page

POM:

`  <dependencies>
      	<dependency>
	        <groupId>com.googlecode.lanterna</groupId>
	        <artifactId>lanterna</artifactId>
	        <version>3.0.0-beta3</version>
    	</dependency>
    </dependencies>`

**Comment by avl42** [comment]
most other terminals i've seen so far didn't allow resizing to 0 height. If this is a common thing on macos to just leave the titlebar visible, then it rather should be fixed...

**Comment by avl42** [comment]
the "it" being lanterna...

**Comment by EnderCrypt** [comment]
i made a quick [gif of it](https://giphy.com/gifs/3oriO0sruzfT2yCa7S)

and the POM im [using](http://prnt.sc/cxzksy)

**Comment by mabe02** [comment]
Oki, let me try...

**Comment by mabe02** [comment]
Alright, reproduced on Linux (Cinnamon) and Win 10

**Comment by avl42** [comment]
maybe, we need to allow for 0 sizes, and add a method to query a
TerminalSize for being denatured...

**Comment by mabe02** [comment]
In this case, the cursor position validator in DefaultVirtualTerminal had some statements in the wrong order, so it allowed a bad position out. I'm sure there are other ways to break this when the size is 0, but this should do it for now.
