### ISSUE TITLE
Exception when adding a Panel with a LinearLayout to a Panel with BorderLayout

### ISSUE THREAD

**Issue by kwantumWare** [mabe02/lanterna#256]
Exception in thread "Thread-4" java.lang.ClassCastException: com.googlecode.lanterna.gui2.BorderLayout$Location cannot be cast to com.googlecode.lanterna.gui2.LinearLayout$LinearLayoutData
	at com.googlecode.lanterna.gui2.LinearLayout.doVerticalLayout(LinearLayout.java:180)
	at com.googlecode.lanterna.gui2.LinearLayout.doLayout(LinearLayout.java:163)
	at com.googlecode.lanterna.gui2.Panel.layout(Panel.java:327)
	at com.googlecode.lanterna.gui2.Panel.access$300(Panel.java:37)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:187)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:176)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:218)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:196)
	at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:176)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:218)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:334)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:318)
	at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:218)
	at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:73)
	at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:127)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:257)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:120)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:219)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:83)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:401)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:268)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:368)

**Comment by avl42** [comment]
Could you show the piece of your code where you wire up the panel and the
Layout?

It seems like you called setLayoutData() on some Component that's managed
by LinearLayout, but passed it a BorderLayout instance.

**Comment by kwantumWare** [comment]
Unfortunately, I cannot. I was impatient and removed the BorderLayout from my code.

**Comment by avl42** [comment]
Well, anyway, if you change the LayoutManager, then you also need to change each affected Component's LayoutData.

That requirement is not very nice, as even the compiler cannot spot such mistakes. Maybe, LayoutManagers ought to check for correct type of LayoutData, and treat unknown types as if they were just null.

**Comment by avl42** [comment]
I just checked that BorderLayout and GridLayout already do check for appropriate LayoutData, only the LinearLayout doesn't.

preparing a PR ...

**Comment by mabe02** [comment]
Excellent, thanks!
