### ISSUE TITLE
Error adding a checkbox to a table

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#26]
```
I am trying to add a checkbox to records in a table to enable operations on 
multiple records and I see this error while showing the window.


java.lang.IllegalArgumentException: TerminalSize.columns cannot be less than 0!
        at com.googlecode.lanterna.terminal.TerminalSize.setColumns(TerminalSize.java:49)
        at com.googlecode.lanterna.gui.TextGraphics.subAreaGraphics(TextGraphics.java:80)
        at com.googlecode.lanterna.gui.component.CommonCheckBox.repaint(CommonCheckBox.java:66)
        at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:136)
        at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:136)
        at com.googlecode.lanterna.gui.component.Table.repaint(Table.java:130)
        at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:136)
        at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:136)
        at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:136)
        at com.googlecode.lanterna.gui.Window.repaint(Window.java:109)
        at com.googlecode.lanterna.gui.GUIScreen.repaint(GUIScreen.java:157)
        at com.googlecode.lanterna.gui.GUIScreen.update(GUIScreen.java:170)
        at com.googlecode.lanterna.gui.GUIScreen.doEventLoop(GUIScreen.java:204)
        at com.googlecode.lanterna.gui.GUIScreen.showWindow(GUIScreen.java:272)

```

Original issue reported on code.google.com by `m.vino...@gmail.com` on 24 Jul 2012 at 3:20

**Comment by mabe02** [comment]
This shouldn't be an issue in Lanterna 3
