### ISSUE TITLE
Thread safety issue in Panel

### ISSUE THREAD

**Issue by nicoulaj** [mabe02/lanterna#287]
I'm randomly getting this error when using the separate thread mode:
```
java.util.ConcurrentModificationException
  at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)                            
  at java.util.ArrayList$Itr.next(ArrayList.java:851)                                              
  at com.googlecode.lanterna.gui2.Panel.updateLookupMap
  at com.googlecode.lanterna.gui2.AbstractComposite.updateLookupMap
  at com.googlecode.lanterna.gui2.AbstractBasePane.draw
  at com.googlecode.lanterna.gui2.AbstractWindow.draw
  at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI
  at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen
  at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen
  at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate
  at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop
  at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000
  at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run
```

Looking at the source of Panel, it seems `components` is inconsistently synchronized:

* not synchronized in `updateLookupMap()`
* not synchronized in `invalidate()`
* synchronized in `addComponent()`
* synchronized in `getChildCount()`
* synchronized in `getChildren()`
* etc...

**Comment by mabe02** [comment]
Looks that way. I've make it all consistent by synchronizing on the collection for all operations.

**Comment by mabe02** [comment]
Pre-emptively closing this in preparation for next release
