### ISSUE TITLE
IllegalStateException on Ctrl-C when not in private mode

### ISSUE THREAD

**Issue by macifell** [mabe02/lanterna#299]
This code:
```
    public static void main(String[] args) throws IOException {
        Terminal t = new DefaultTerminalFactory().createTerminal();
        t.readInput();
        t.close();
    }
```
Produces the following exception when ctrl-c is entered:
```
Exception in thread "main" java.lang.IllegalStateException: Cannot call exitPrivateMode() when not in private mode
	at com.googlecode.lanterna.terminal.ansi.ANSITerminal.exitPrivateMode(ANSITerminal.java:233)
	at com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal.isCtrlC(UnixLikeTerminal.java:184)
	at com.googlecode.lanterna.terminal.ansi.UnixLikeTerminal.readInput(UnixLikeTerminal.java:111)
	at xxxx.yyyy.main(yyyy.java:nn)
```
The application was running in Gnome Terminal 3.18.3 on Linux.

**Comment by avl42** [comment]
good catch.   Probably UnixLikeTerminal.isCtrlC should just catch it, or
check the private mode first.
