### ISSUE TITLE
Deadlock issue with buttons and preferedSize

### ISSUE THREAD

**Issue by Raphi111** [mabe02/lanterna#304]
Using the latest release I keep getting a deadlock: 

```
Java stack information for the threads listed above:
===================================================
"LanternaGUI":
        at com.googlecode.lanterna.gui2.AbstractComponent.calculatePreferredSize(AbstractComponent.java:194)
        - waiting to lock <0x00000000c6dd5630> (a com.googlecode.lanterna.gui2.Button)
        at com.googlecode.lanterna.gui2.AbstractComponent.getPreferredSize(AbstractComponent.java:178)
        at com.googlecode.lanterna.gui2.GridLayout.getPreferredColumnWidths(GridLayout.java:525)
        at com.googlecode.lanterna.gui2.GridLayout.doLayout(GridLayout.java:419)
        at com.googlecode.lanterna.gui2.Panel.layout(Panel.java:350)
        - locked <0x00000000c6dd55e0> (a java.util.ArrayList)
        at com.googlecode.lanterna.gui2.Panel.access$300(Panel.java:37)
        at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:195)
        at com.googlecode.lanterna.gui2.Panel$1.drawComponent(Panel.java:182)
        at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:218)
        - locked <0x00000000c6dd5588> (a com.googlecode.lanterna.gui2.Panel)
        at com.googlecode.lanterna.gui2.Borders$AbstractBorderRenderer.drawComponent(Borders.java:279)
        at com.googlecode.lanterna.gui2.Borders$AbstractBorderRenderer.drawComponent(Borders.java:176)
        at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:218)
        - locked <0x00000000c6dd5530> (a com.googlecode.lanterna.gui2.Borders$SingleLine)
        at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:338)
        at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.drawComponent(AbstractBasePane.java:322)
        at com.googlecode.lanterna.gui2.AbstractComponent.draw(AbstractComponent.java:218)
        - locked <0x00000000c6dd54e0> (a com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder)
        at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:73)
        at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:127)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:259)
        - locked <0x00000000c6dd4e60> (a com.googlecode.lanterna.gui2.MultiWindowTextGUI)
        at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:120)
        - locked <0x00000000c6dd4e60> (a com.googlecode.lanterna.gui2.MultiWindowTextGUI)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:221)
        - locked <0x00000000c6dd4e60> (a com.googlecode.lanterna.gui2.MultiWindowTextGUI)
        at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:83)
        - locked <0x00000000c6dd4f48> (a com.googlecode.lanterna.gui2.SeparateTextGUIThread)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:114)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:44)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:55)
"main":
        at com.googlecode.lanterna.gui2.Panel.invalidate(Panel.java:340)
        - waiting to lock <0x00000000c6dd55e0> (a java.util.ArrayList)
        at com.googlecode.lanterna.gui2.AbstractComposite.invalidate(AbstractComposite.java:110)
        at com.googlecode.lanterna.gui2.AbstractComposite.invalidate(AbstractComposite.java:110)
        at com.googlecode.lanterna.gui2.AbstractBasePane.invalidate(AbstractBasePane.java:66)
        at com.googlecode.lanterna.gui2.AbstractBasePane.setFocusedInteractable(AbstractBasePane.java:250)
        at com.googlecode.lanterna.gui2.AbstractBasePane.setFocusedInteractable(AbstractBasePane.java:230)
        at com.googlecode.lanterna.gui2.AbstractInteractableComponent.takeFocus(AbstractInteractableComponent.java:53)
        - locked <0x00000000c6dd5630> (a com.googlecode.lanterna.gui2.Button)
        at g43317.zebras.view.UserInterface_lanterna.displayImpalaView(UserInterface_lanterna.java:215)
        at g43317.zebras.Zebras_lanterna.play(Zebras_lanterna.java:121)
        at g43317.zebras.Zebras_lanterna.main(Zebras_lanterna.java:71)

Found 1 deadlock.
```
I can't reproduce it on a small example but as soon as I'm able to I will post it here.
Most of the time I get a deadlock when I try to .takeFocus() on a Button or I try to disable a whole list of Buttons.
I'm making a GUI for a game and it works fine, except with this issue that I almost always have at some point in the game, and I don't know any workaround yet. 
I think it's a different issue from #295 as I don't try to resize the screen.
I got the issue in Netbeans and Swing terminal but I suspect it happens with xterm too.

**Comment by mabe02** [comment]
Now that's a classic deadlock. Seems I've been a bit too generous with synchronized keywords in the GUI code.

**Comment by mabe02** [comment]
Okay, I think I have pushed a change that will solve this. Multi-thread access is always tricky. The workaround is to synchronize by using `TextGUI.getGUIThread().invokeLater(..)`
