### ISSUE TITLE
TextBox Scrolling

### ISSUE THREAD

**Issue by Janrupf** [mabe02/lanterna#316]
So I'm trying to build an console with the API, but I'm having an simple problem: The TextBox is not scrolling down automaticly, are im down something wrong?

```
consoleOut.addLine("msg");
```

After repeating this, the firt line is still on Top.

**Comment by avl42** [comment]
that's a feature.

the textbox is a simple editor, not a "terminal". you would need to either
delete the first few lines until the last one becomes visible, or move the
cursor to bottom, by "sending" it a few Down keystrokes...

Am 09.07.2017 17:41 schrieb "Janrupf" <notifications@github.com>:

**Comment by Janrupf** [comment]
Yeah, but 
```
consoleOut.addLine(line);
consoleOut.handleKeyStroke(new KeyStroke(KeyType.ArrowDown));
```

will result in: 
```
at com.googlecode.lanterna.gui2.AbstractComponent.getRenderer(AbstractComponent.java:137)
	at com.googlecode.lanterna.gui2.AbstractInteractableComponent.getRenderer(AbstractInteractableComponent.java:109)
	at com.googlecode.lanterna.gui2.TextBox.getRenderer(TextBox.java:197)
	at com.googlecode.lanterna.gui2.TextBox.handleKeyStrokeReadOnly(TextBox.java:619)
	at com.googlecode.lanterna.gui2.TextBox.handleKeyStroke(TextBox.java:451)
	at net.jan.console.ConsoleManager.writeLineToConsole(ConsoleManager.java:143)
        [...]
```

**Comment by avl42** [comment]
that's a theme related NPE. You also need to add the ressources folder as
"source folders", iirc.

please step through the DefaultTerminalFactory in single-step mode, and let
us know, which terminal implementation it was trying to use and which it ended
up using.


Am 10.07.2017 16:26 schrieb "Janrupf" <notifications@github.com>:

Yeah, but

consoleOut.addLine(line);
consoleOut.handleKeyStroke(new KeyStroke(KeyType.ArrowDown));

will result in:

at com.googlecode.lanterna.gui2.AbstractComponent.getRenderer(AbstractComponent.java:137)
	at com.googlecode.lanterna.gui2.AbstractInteractableComponent.getRenderer(AbstractInteractableComponent.java:109)
	at com.googlecode.lanterna.gui2.TextBox.getRenderer(TextBox.java:197)
	at com.googlecode.lanterna.gui2.TextBox.handleKeyStrokeReadOnly(TextBox.java:619)
	at com.googlecode.lanterna.gui2.TextBox.handleKeyStroke(TextBox.java:451)
	at net.jan.console.ConsoleManager.writeLineToConsole(ConsoleManager.java:143)
        [...]

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mabe02/lanterna/issues/316#issuecomment-314122184>, or mute
the thread

**Comment by Janrupf** [comment]
So, using automatic mode (DefaultTerminalFactory.createTerminal()) resultet in Swing (cause im on Windows running in eclipse). This just happens one time, I think its because there is no line to go down, but I'm not shure.

**Comment by avl42** [comment]
if you're on some 'headless' system, it should pick the non-swing jna
thing...

Am 10.07.2017 22:07 schrieb "Janrupf" <notifications@github.com>:

**Comment by avl42** [comment]
ps: i think we now got the two issues (textbox versus terminal) mixed up.

can you reproduce the NPE for synthetic cursor down  also with
swingterminal?

Am 10.07.2017 23:24 schrieb :

**Comment by Janrupf** [comment]
Actually I'm writing an native for the Terminal for my self. But I will take a look.

**Comment by mabe02** [comment]
The Theme NPE is a bit weird, I'm suspecting the theme resources are not correctly on the classpath somehow... We should consider embedding the default theme in the code I think, as a fall-back.
