### ISSUE TITLE
NPE in AbstractWindow::fromGlobal (contentOffset is null) 

### ISSUE THREAD

**Issue by evansdom** [mabe02/lanterna#318]
java.lang.NullPointerException
        at com.googlecode.lanterna.gui2.AbstractWindow.fromGlobal(AbstractWindow.java:154)
        at com.googlecode.lanterna.gui2.AbstractBasePane.doHandleInput(AbstractBasePane.java:115)
        at com.googlecode.lanterna.gui2.AbstractBasePane.handleInput(AbstractBasePane.java:97)
        at com.googlecode.lanterna.gui2.AbstractWindow.handleInput(AbstractWindow.java:132)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.handleInput(MultiWindowTextGUI.java:333)
        at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:94)
        at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:75)
        at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:406)
        at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:268)
        at com.googlecode.lanterna.gui2.dialogs.DialogWindow.showDialog(DialogWindow.java:54)
        at my.StackTraceDialog.showDialog(StackTraceDialog.java:73)
        at my.StackTraceDialog.doDialog(StackTraceDialog.java:143)
        at my.StackTraceDialog.DISPLAY(StackTraceDialog.java:101)
        at my.StackTraceDialog.display(StackTraceDialog.java:88)
        at my.Pmc.onUnhandledKeyStroke(Pmc.java:389)
        at com.googlecode.lanterna.gui2.AbstractTextGUI.fireUnhandledKeyStroke(AbstractTextGUI.java:173)
        at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:96)
        at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:75)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread.mainGUILoop(SeparateTextGUIThread.java:114)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread.access$000(SeparateTextGUIThread.java:44)
        at com.googlecode.lanterna.gui2.SeparateTextGUIThread$1.run(SeparateTextGUIThread.java:55)

    @Override
    public TerminalPosition fromGlobal(TerminalPosition globalPosition) {
        if(globalPosition == null) {
            return null;
        }
        return globalPosition.withRelative(
                -lastKnownPosition.getColumn() - contentOffset.getColumn(),
                -lastKnownPosition.getRow() - contentOffset.getRow());
    }

In the debugger I find that contentOffset is null.

**Comment by avl42** [comment]
My interpretation is, that triggered by a keystroke you want to open a modal popup window (so far so good) and the popup window is asked to process a mouseevent before it was even drawn.

The root cause might be that "processEventsAndUpdate()" does exactly what it says: it first processes events, and only then does (eventually) an update.  This probably doesn't matter with usual typing, but with mouseactions needing that contentOffset already set (which only gets set in MultiWindowTextGUI.drawGUI()) then it breaks.

I don't know if the mouseevent that triggered it was a "precious" one (a click or release) or just a move event.  for the latter case it might be enough to initialize the contentOffset to a (0,0) position, otherwise we might need to really fix it and insert an explicit update before going into processEventsAndUpdate().

**Comment by mabe02** [comment]
I've added a little bit of protective code around this so it doesn't NPE, but there's probably a better fix that could be done here if we understand the issue better.
