### ISSUE TITLE
UnsupportedOperationException on MessageDialogBuilder#setExtraWindowHints

### ISSUE THREAD

**Issue by andysenn** [mabe02/lanterna#353]
Hello,

First of all, I love Lanterna. Thank you so much for your hard work on this project.

When I call MessageDialogBuilder#setExtraWindowHints(...), it throws an UnsupportedOperationException. It looks like this is because the Iterator<T> from the underlying Set<T> implementation for hints does not support the #remove() operation.

Here is the full stack trace:

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.util.Collections$1.remove(Collections.java:4684)
	at java.util.AbstractCollection.clear(AbstractCollection.java:436)
	at com.googlecode.lanterna.gui2.dialogs.MessageDialogBuilder.setExtraWindowHints(MessageDialogBuilder.java:94)
	at com.jamfsoftware.tools.jss.initializer.ui.cli.CLIApplication.showMessageBox(CLIApplication.kt:266)
	at com.jamfsoftware.tools.jss.initializer.ui.cli.CLIApplication.validate(CLIApplication.kt:249)
	at com.jamfsoftware.tools.jss.initializer.ui.cli.CLIApplication.execute(CLIApplication.kt:257)
	at com.jamfsoftware.tools.jss.initializer.ui.cli.CLIApplication.access$execute(CLIApplication.kt:20)
	at com.jamfsoftware.tools.jss.initializer.ui.cli.CLIApplication$start$$inlined$apply$lambda$14.run(CLIApplication.kt:103)
	at com.googlecode.lanterna.gui2.Button$1.onTriggered(Button.java:74)
	at com.googlecode.lanterna.gui2.Button.triggerActions(Button.java:101)
	at com.googlecode.lanterna.gui2.Button.handleKeyStroke(Button.java:93)
	at com.googlecode.lanterna.gui2.AbstractInteractableComponent.handleInput(AbstractInteractableComponent.java:142)
	at com.googlecode.lanterna.gui2.AbstractBasePane.doHandleInput(AbstractBasePane.java:126)
	at com.googlecode.lanterna.gui2.AbstractBasePane.handleInput(AbstractBasePane.java:97)
	at com.googlecode.lanterna.gui2.AbstractWindow.handleInput(AbstractWindow.java:133)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.handleInput(MultiWindowTextGUI.java:333)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.processInput(AbstractTextGUI.java:94)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:75)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:406)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:269)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:370)
	at com.jamfsoftware.tools.jss.initializer.ui.cli.CLIApplication.start(CLIApplication.kt:39)
	at com.jamfsoftware.tools.jss.initializer.AppMainKt.main(AppMain.kt:5)
```

Please note that the implementing code is written in Kotlin, but that doesn't seem to be of consequence here.

Please let me know if there is any additional information that I can provide!

**Comment by andysenn** [comment]
The call to #setExtraWindowHints(...) in this case is simply:

```
setHints(listOf(Window.Hint.FULL_SCREEN, Window.Hint.MODAL))
```

**Comment by andysenn** [comment]
I believe that this is because the constructor uses:

```
this.extraWindowHints = Collections.singleton(Window.Hint.CENTERED);
```

```Collections.singleton(...)``` returns an immutable set.

**Comment by mabe02** [comment]
Just merged that, thanks!
