### ISSUE TITLE
Horizontal span 3+ cause java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AlainCo** [mabe02/lanterna#358]
Hi,
I use Lanterna 3.0.0 on windows in Swing mode (under Eclipse, java8).

I just try to use a GridLayout (eg 5 column)

and it seems that whatever I do, any widget with a layoutdata with horizontalspan 3 and more cause a java.lang.ArrayIndexOutOfBoundsException
is it a known restriction, or should I investigate in a stupid mistake of mine?

I've tested many variation, with Lebel, textbox, EmptySpace, and any span above 2 cause a crash...
I imagine I've done a basic mistake.

```
                int nbColumns = 5;
		final Window window = new BasicWindow(title);

		final GridLayout layoutManager = new GridLayout(nbColumns);
		layoutManager.setVerticalSpacing(0);
		layoutManager.setHorizontalSpacing(1);
		final Panel contentPanel = new Panel(layoutManager);
               contentPanel.addComponent(
			new EmptySpace().setLayoutData(GridLayout.createLayoutData(Alignment.CENTER, Alignment.CENTER, false, false,3, 1)));
               window.setComponent(contentPanel);
		textGUI.addWindowAndWait(window);
```

produces

> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at com.googlecode.lanterna.gui2.GridLayout.getPreferredColumnWidths(GridLayout.java:542)
	at com.googlecode.lanterna.gui2.GridLayout.getPreferredSize(GridLayout.java:387)
	at com.googlecode.lanterna.gui2.Panel$1.getPreferredSize(Panel.java:187)
	at com.googlecode.lanterna.gui2.Panel$1.getPreferredSize(Panel.java:182)
	at com.googlecode.lanterna.gui2.AbstractComponent.calculatePreferredSize(AbstractComponent.java:194)
	at com.googlecode.lanterna.gui2.Panel.calculatePreferredSize(Panel.java:217)
	at com.googlecode.lanterna.gui2.AbstractComponent.getPreferredSize(AbstractComponent.java:178)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.getPreferredSize(AbstractBasePane.java:331)
	at com.googlecode.lanterna.gui2.AbstractBasePane$ContentHolder$1.getPreferredSize(AbstractBasePane.java:324)
	at com.googlecode.lanterna.gui2.AbstractComponent.calculatePreferredSize(AbstractComponent.java:194)
	at com.googlecode.lanterna.gui2.AbstractComponent.getPreferredSize(AbstractComponent.java:178)
	at com.googlecode.lanterna.gui2.AbstractWindow.getPreferredSize(AbstractWindow.java:161)
	at com.googlecode.lanterna.gui2.DefaultWindowManager.onAdded(DefaultWindowManager.java:103)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindow(MultiWindowTextGUI.java:356)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:369)

**Comment by avl42** [comment]
Well, it probably shouldn't happen, so it is certainly a bug.

I had a look at the source, but it's a bit complicated.
The heuristics are that there must be a first row of components of which none should have a columnspan, just so that the actual number of columns can be obtained. (It's possible after all, that there are fewer components than the GridLayout's parameter.

Now, if a column doesn't have any component on its own, but only components of previous columns overlapping it, then there exists no reasonable width for that column (and none for the previous column, either).

In your real case at hand, would it be possible to add a first row of not-column-spanning simple components, and then see, if you can add column-spanning components in the later rows?

Note, that columns that are only covered by spanning can be really left out. They don't serve any purpose (except for revealing bugs, at least :-) ).

I'll look into it more closely later (maybe only in a few weeks, though), because even such fringe-cases should be handled without throwing a tantrum...

**Comment by avl42** [comment]
I really think, that this "looking at the first row" is a bug.   The columnWidths[]'s length always should be the declared width for the GridLayout, and any unused columns just ought to be set to 0.

**Comment by AlainCo** [comment]
I start to understand the kind of problems.
maybe I could make it work better by setting exact size of some columns, filling with real content, real size, instead of trying to understand why it crashes by removing lines...
a first row with real width could do the job,
I should also avoid span on never individual columns.
 I will try soon.

Thanks, no surprise I had problem...

**Comment by mabe02** [comment]
It's too bad we couldn't use the SWT GridLayout code  :(

**Comment by mabe02** [comment]
Looks like the problem is in `GridLayout#eliminateUnusedRowsAndColumns`, even with a span = 3 it reduces the 5 columns of the tables to 2.

**Comment by mabe02** [comment]
Okay, I'm a little bit worried I've broken something but because the method mentioned above has a critical bug where it doesn't adjusts spans accordingly, I've decided to move ahead anyway. The new code will only remove rows/columns that are all set to null.
