### ISSUE TITLE
NullPointerException when adding a TextBox inside a Panel that is itself in another Panel

### ISSUE THREAD

**Issue by linouxis9** [mabe02/lanterna#359]
Hello,

A NullPointerException occurs when adding a TextBox inside a Panel that is itself in another Panel like shown in the the Tutorial.

I've tested different components and this issue is only reproducible with a TextBox.

Thank you!

```java
import com.googlecode.lanterna.*;
import com.googlecode.lanterna.gui2.*;
import com.googlecode.lanterna.screen.*;
import com.googlecode.lanterna.terminal.*;

import java.io.IOException;
import java.util.Arrays;
import java.util.regex.Pattern;

public class CLI {
    public CLI() {
		try {
			Terminal terminal;
			Screen screen = null;
			terminal = new DefaultTerminalFactory().createTerminal();
	
	        screen = new TerminalScreen(terminal);
	        screen.startScreen();
	
	    	Panel mainPanel = new Panel();
	    	mainPanel.setLayoutManager(new LinearLayout(Direction.HORIZONTAL));
	
	    	Panel leftPanel = new Panel();
	    	mainPanel.addComponent(leftPanel.withBorder(Borders.singleLine("Registers")));
	
	    	Panel centerPanel = new Panel();
	    	mainPanel.addComponent(centerPanel.withBorder(Borders.singleLine("Editor")));
	    	centerPanel.addComponent(new TextBox(new TerminalSize(10,10)));

	    	Panel rightPanel = new Panel();
	    	mainPanel.addComponent(rightPanel.withBorder(Borders.singleLine("Memory")));
	
	    	Window window = new BasicWindow();
	        window.setComponent(mainPanel);
	    	window.setHints(Arrays.asList(Window.Hint.CENTERED));
	    	
	    	window.setComponent(mainPanel.withBorder(Borders.singleLine("@rmsim#")));
	        MultiWindowTextGUI gui = new MultiWindowTextGUI(screen, new DefaultWindowManager(), new EmptySpace(TextColor.ANSI.BLUE));
	        gui.addWindowAndWait(window);
		} catch (IOException e) {
			e.printStackTrace();
		}
    }
}
```
Backtrace: 
```java
Exception in thread "main" java.lang.NullPointerException
	at com.googlecode.lanterna.gui2.AbstractBorder.toBasePane(AbstractBorder.java:64)
	at com.googlecode.lanterna.gui2.AbstractComponent.toBasePane(AbstractComponent.java:340)
	at com.googlecode.lanterna.gui2.AbstractComponent.toBasePane(AbstractComponent.java:340)
	at com.googlecode.lanterna.gui2.InteractableLookupMap.add(InteractableLookupMap.java:61)
	at com.googlecode.lanterna.gui2.Panel.updateLookupMap(Panel.java:330)
	at com.googlecode.lanterna.gui2.AbstractComposite.updateLookupMap(AbstractComposite.java:144)
	at com.googlecode.lanterna.gui2.Panel.updateLookupMap(Panel.java:327)
	at com.googlecode.lanterna.gui2.AbstractComposite.updateLookupMap(AbstractComposite.java:144)
	at com.googlecode.lanterna.gui2.AbstractComposite.updateLookupMap(AbstractComposite.java:144)
	at com.googlecode.lanterna.gui2.AbstractBasePane.draw(AbstractBasePane.java:80)
	at com.googlecode.lanterna.gui2.AbstractWindow.draw(AbstractWindow.java:128)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.drawGUI(MultiWindowTextGUI.java:259)
	at com.googlecode.lanterna.gui2.AbstractTextGUI.updateScreen(AbstractTextGUI.java:120)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.updateScreen(MultiWindowTextGUI.java:221)
	at com.googlecode.lanterna.gui2.AbstractTextGUIThread.processEventsAndUpdate(AbstractTextGUIThread.java:83)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:406)
	at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:269)
	at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:370)
	at CLI.<init>(CLI.java:41)
	at Main.main(Main.java:14)
```

**Comment by avl42** [comment]
I could reproduce it, but don't yet know what causes it, nor how to fix it.

I intend to look into it again, (with a slight hope that @mabe02 checks it, too)
but for now a message to not leave this unanswered for even longer...

**Comment by avl42** [comment]
I don't yet have a solution for why this test program crashes, but I tried a few things and confined the bug a bit closer.

1) Any *interactive* component will do in place of the TextBox, like a Button (but not a Label)
2) A relevant ingredient is that you do "window.addComponent(mainPanel )" once, and then replace the mainPanel by a bordered version of itself. 

I guess the second one could help you workaround it: just remove the window.setComponent(mainPanel); line (the one between "new BasicWindow()" and "setHints").

I'm still trying to find the real bug.

It certainly *should* be possible to replace a component by itself bordered.

**Comment by avl42** [comment]
Next observation is that a Border slips into the gap between Containers and Interactables. It is neither of these, and thus doesn't properly propagate the setting up of focus-related state.

I think, a Border should (pretend to) be a Container as well, even if it won't ever directly hold more than a single component.

**Comment by avl42** [comment]
Next one...  both of the Panels were not relevant.
```
            Window window = new BasicWindow();
            Button button = new Button("Hello");
            window.setComponent(button);
            window.setComponent(button.withBorder(Borders.singleLine("Border")));
```
(apart from Screen and MultiWindowTextGUI boilerplates) also triggers it.

It *is* relevant, that the previously added component is the identical one as the one then wrapped in a Border and re-added.

**Comment by avl42** [comment]
sorry for the noise... I didn't know how to do the rebase other than as a new PR.

**Comment by linouxis9** [comment]
Perfect! Thank you!

**Comment by avl42** [comment]
Thanks to you for reporting!
