### ISSUE TITLE
waitUntilClosed don't return or throw exception when socket is closed.

### ISSUE THREAD

**Issue by realkcn** [mabe02/lanterna#417]
I write a telnet server like the example [com/googlecode/lanterna/gui2/GUIOverTelnet.java](https://github.com/mabe02/lanterna/blob/master/src/test/java/com/googlecode/lanterna/gui2/GUIOverTelnet.java).
When the client use ctrl+] to force closing telnet socket, the thread don't exit.
Seem it is infinite loop in function waitForWindowToClose and can't detect the socket is closed.

Call Stack below:
"Thread-0@590" prio=5 tid=0xd nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at com.googlecode.lanterna.gui2.MultiWindowTextGUI.waitForWindowToClose(MultiWindowTextGUI.java:421)
	  at com.googlecode.lanterna.gui2.AbstractWindow.waitUntilClosed(AbstractWindow.java:269)
	  at com.googlecode.lanterna.gui2.MultiWindowTextGUI.addWindowAndWait(MultiWindowTextGUI.java:373)
	  at cn.kcn.term.server.TestMain.runGUI(TestMain.java:157)
	  at cn.kcn.term.server.TestMain.access$000(TestMain.java:35)
	  at cn.kcn.term.server.TestMain$1.run(TestMain.java:47)

**Comment by avl42** [comment]
My own single-stepping test with GUIOverTelnet makes it look like a ServerSocket just simply doesn't let us know that the client is gone, if the client types Ctrl-] and "close" in telnet. 

I got as far as stepping through AbstractPlainSocketImpl.available() and all it reports is "no data at the moment" - specifically it hasn't even noticed that the socket is broken.

It seems to me, at least at this time, that Lanterna cannot do much about it.

**Comment by realkcn** [comment]
> My own single-stepping test with GUIOverTelnet makes it look like a ServerSocket just simply doesn't let us know that the client is gone, if the client types Ctrl-] and "close" in telnet.
> 
> I got as far as stepping through AbstractPlainSocketImpl.available() and all it reports is "no data at the moment" - specifically it hasn't even noticed that the socket is broken.
> 
> It seems to me, at least at this time, that Lanterna cannot do much about it.

It need some notify to break the windows event loop.
TelnetTerminal.available() method should throw EOFException when socket is closed. waitForWindowToClose method will catch the EOFException and quit the loop.

Is it possible?

**Comment by avl42** [comment]
To me it looks like a bug in Java, but it would be such a fundamental one that I just can't believe that it would persist for so long.

I've created an SSCCE (Small Self-Contained Compile-able Example) on a Java forum.  Maybe they know more than me: https://groups.google.com/forum/#!topic/comp.lang.java.programmer/JkQzyKdm8es

**Comment by avl42** [comment]
According to forum replies, we just picked some bad approach. Apparently, method "available()" of a stream just isn't meant/designed to detect/report EOF on a socket.  I'll keep looking for alternative approaches.

**Comment by realkcn** [comment]
According to java socket, I think only two solutions can resolve the problem.
1. use block read，change the behavior of  event loop in lanterna window.
2. use the nio socket for jdk 1.7+

**Comment by mabe02** [comment]
I was thinking of moving to Java 8 on version 3.1 (master branch) but for 3.0 we are sticking to Java 6 :)

**Comment by mabe02** [comment]
We might want to set a socket timeout to 1 ms and try a blocking read if available() returns 0, just to see if the socket is broken or not. Not super elegant but if it works it might be ok.

**Comment by realkcn** [comment]
> I was thinking of moving to Java 8 on version 3.1 (master branch) but for 3.0 we are sticking to Java 6 :)

Good news, I like it! Java 8 is powerful than 6.

**Comment by avl42** [comment]
I'm thinking of hooking into the ".available()" method of TelnetTerminal.TelnetClientIACFilterer .
If both `underlyingStreamAvailable == 0 && bytesInBuffer == 0` then we could try to set the timeout to 1ms and attempt to fillBuffer(). For this, the class might need to be passed the socket directly, not just its InputStream.

**Comment by mabe02** [comment]
Agreed, although I think we could also add another filter in between that and the input stream for this specific purpose

**Comment by mabe02** [comment]
Okay, I've created a PR for adding an extra layer on top of the socket input stream. It's really ugly (as raw socket code tends to be) but in my testing it works now with both this case and with the previous telnet tests.
