### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by Saint-Theana** [mabe02/lanterna#425]
This is the problem that troubling me.
I had to merge all lanterna's classes and my project's classes into one jar to make it work.
When I devide those two guy I got this:

Exception in thread "Thread-0" java.lang.ExceptionInInitializerError                                                                          at com.googlecode.lanterna.gui2.AbstractTextGUI.<init>(AbstractTextGUI.java:60)                                                       at com.googlecode.lanterna.gui2.MultiWindowTextGUI.<init>(MultiWindowTextGUI.java:157)                                                at com.googlecode.lanterna.gui2.MultiWindowTextGUI.<init>(MultiWindowTextGUI.java:147)                                                at com.googlecode.lanterna.gui2.MultiWindowTextGUI.<init>(MultiWindowTextGUI.java:126)                                                at com.googlecode.lanterna.gui2.MultiWindowTextGUI.<init>(MultiWindowTextGUI.java:107)                                                at com.googlecode.lanterna.gui2.MultiWindowTextGUI.<init>(MultiWindowTextGUI.java:90)                                                 at com.googlecode.lanterna.gui2.MultiWindowTextGUI.<init>(MultiWindowTextGUI.java:60)                                                 at com.Tick_Tock.PCTIM.MainApp.initterminal(MainApp.java:244)                                                                         at com.Tick_Tock.PCTIM.MainApp.run(MainApp.java:65)        Caused by: java.lang.NullPointerException                                  at com.googlecode.lanterna.bundle.LanternaThemes.loadPropTheme(LanternaThemes.java:110)                                               at com.googlecode.lanterna.bundle.LanternaThemes.<clinit>(LanternaThemes.java:46)                                                     ... 9 more

**Comment by avl42** [comment]
make sure you also add the ressources to lanterna's jar file.


>

**Comment by Saint-Theana** [comment]
what resources?
It's that my project's classes files?

**Comment by avl42** [comment]
I meant the directory  src/main/resources/  in lanterna's project root for the sources.

If you got lanterna as a binary package, the jar file likely has a couple of files ending in ".properties" - you may have these files in that "all-in-one" jar file, but upon separation of lanterna and your app, you might have forgotten these files, or left them in the wrong jar file. I'm just guessing.
