### ISSUE TITLE
Error from lanterna while showing a wide table on a window

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#49]
```
I run into this issue and start getting exceptions in an infinite loop when I 
show a table that's wider than a certain width. This happens with v2.1.1 of 
lanterna. I am attaching the source file that reproduces this issue here. 
However I was able to get the same code working with v2.0.3 of lanterna(with 
minor API related changes ofcourse).

Generated exception

java.lang.IllegalArgumentException: TerminalSize.columns cannot be less than 0!
    at com.googlecode.lanterna.terminal.TerminalSize.setColumns(TerminalSize.java:49)
    at com.googlecode.lanterna.gui.TextGraphics.subAreaGraphics(TextGraphics.java:111)
    at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:143)
    at com.googlecode.lanterna.gui.component.Table.repaint(Table.java:147)
    at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:147)
    at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:147)
    at com.googlecode.lanterna.gui.component.Panel.repaint(Panel.java:147)
    at com.googlecode.lanterna.gui.Window.repaint(Window.java:133)
    at com.googlecode.lanterna.gui.GUIScreen.repaint(GUIScreen.java:187)
    at com.googlecode.lanterna.gui.GUIScreen.update(GUIScreen.java:200)
    at com.googlecode.lanterna.gui.GUIScreen.doEventLoop(GUIScreen.java:235)
    at com.googlecode.lanterna.gui.GUIScreen.showWindow(GUIScreen.java:307)
    at com.googlecode.lanterna.gui.GUIScreen.showWindow(GUIScreen.java:263)
    at TestMain.main(TestMain.java:65)
```

Original issue reported on code.google.com by `m.vino...@gmail.com` on 15 Nov 2012 at 7:05

Attachments:
- [TestMain.java](https://storage.googleapis.com/google-code-attachments/lanterna/issue-49/comment-0/TestMain.java)

**Comment by evansdom** [comment]
I have hit a similar issue. DefaultWindowDecorationRenderer.draw() returns calling newTextGraphics( ... -2 on relative columns.

Version:
./target/lanterna-3.0.0-SNAPSHOT.jar  June 2 2017

I have fixed TerminalSize in my copy and the issue is gone:

        if(delta <= 0) {   // was ==
            return this;
        }

**Comment by evansdom** [comment]
UPDATE: Bad workaround, since it ruins the bottom of the window. However, issue remains.

![image](https://user-images.githubusercontent.com/29444430/27703368-fa88dce4-5cbb-11e7-8305-3cc0a0c3b6ac.png)


I have hit a similar issue. DefaultWindowDecorationRenderer.draw() returns calling newTextGraphics( ... -2 on relative columns.

Version:
./target/lanterna-3.0.0-SNAPSHOT.jar June 2 2017

I have fixed TerminalSize in my copy and the issue is gone:

    if(delta <= 0) {   // was ==
        return this;
    }

**Comment by mabe02** [comment]
I've adjusted DefaultWindowDecorationRenderer to deal with this

**Comment by evansdom** [comment]
Many thanks.
