### ISSUE TITLE
Unable to figure out how to close an application - explanations missing in the docs

### ISSUE THREAD

**Issue by notsodistantworlds** [mabe02/lanterna#523]
The docs are a bit of a stub in general, but the following 2 things in the docs (or the lack of them, should i say) stand out:

 - I was not able to find any docs on how to make the lanterna app shut down when CTRL+C is pressed. Is this supported? This is a typical way of killing console programs, including the similar ASCII UI tools like `atop`, `iftop`, etc.
 - I did not find any explanation on how to operate a Swing terminal nor an AWT terminal. The Swing terminal crashes with the following:
```
Exception in thread "main" java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at com.googlecode.lanterna.terminal.swing.GraphicalTerminalImplementation.ensureGraphicBufferHasRightSize(GraphicalTerminalImplementation.java:499)
	at com.googlecode.lanterna.terminal.swing.GraphicalTerminalImplementation.updateBackBuffer(GraphicalTerminalImplementation.java:333)
	at com.googlecode.lanterna.terminal.swing.GraphicalTerminalImplementation.flush(GraphicalTerminalImplementation.java:799)
	at com.googlecode.lanterna.terminal.swing.GraphicalTerminalImplementation.enterPrivateMode(GraphicalTerminalImplementation.java:665)
	at com.googlecode.lanterna.terminal.swing.SwingTerminal.enterPrivateMode(SwingTerminal.java:224)
	at com.googlecode.lanterna.terminal.swing.SwingTerminalFrame.enterPrivateMode(SwingTerminalFrame.java:237)
	at com.googlecode.lanterna.screen.TerminalScreen.startScreen(TerminalScreen.java:91)
	at nsdw.utils.ClientKt.main(Client.kt:19)
```
The AWT terminal just doesn't do anything. The program prints nothing and can still be interrupted with CTRL+C.

I thought i could use these emulated terminals to have a new window that i could close to stop the program.

I know the docs suggest creating a button element and adding a runnable to it which would stop the program, but that seems hacky and unnecessary. Every terminal already has an obvious way of doing that, CTRL+C. And if not that, then creating a terminal emulator window and then closing it should work well enough as a substitute, at least for my use case. But, again, that doesn't work, either.

**Comment by avl42** [comment]
I believe to spot a few misunderstandings here... 

Not all Terminal-applications are terminated by Ctrl-C.     There are mostly two categories of terminal applications:   plain stdin/-out/-err apps (which almost all terminate on Ctrl-C)  and  so called "text GUI" apps, like e.g. editors, mail-apps, irc-clients, nntp-clients, which only rarely quit on Ctrl-C.    Lanterna is a library to create the second type of applications.

AWT and Swing terminals can be mostly thought of as a "workaround" for platforms without proper native terminals, although there are also legit reasons why one would use them on Linux,Unix,Mac...

It is not necessary to use buttons - I know because my current lanterna-using application just makes use of the screen-layer, not the TextGui layer.

**Comment by notsodistantworlds** [comment]
Well alright, but still, is it not possible to make this configurable? Quitting on CTRL+C sounds reasonable enough and should at least be an option.

Could you provide some example code for starting a Swing terminal? Or a link to the docs, perhaps i missed it. So far i've not been able to start an emulated terminal.

**Comment by mabe02** [comment]
You can set a custom CTRL+C behavior for "real" text terminal through UnixLikeTerminal.CtrlCBehaviour, which determines if the signal should be trapped and interpreted by your application on passed on to the JVM (which effectively kills the app).

There is plenty of example code for creating a SwingTerminal/AWTTerminal if you check under the test directory of the source. Although to avoid repetition we have a utility class that contains most of the initialization logic for most of the tests. If you want to display a simple terminal emulator window, just create a SwingTerminalFrame like you would create any JFrame and set it to visible.
