### ISSUE TITLE
Problem using module-info.java

### ISSUE THREAD

**Issue by Quilsen** [mabe02/lanterna#588]
Exception in thread "main" java.lang.IllegalAccessError: class org.example.main.Tui (in module MP3) cannot access class com.googlecode.lanterna.gui2.menu.MenuBar (in module com.googlecode.lanterna) because module com.googlecode.lanterna does not export com.googlecode.lanterna.gui2.menu to module MP3
	at MP3/org.example.main.Tui.runTui(Tui.java:34)
	at MP3/org.example.main.Main.main(Main.java:11)

Process finished with exit code 1

**Comment by avl42** [comment]
Lanterna's `com.googlecode.lanterna.gui2.menu`  is exported within src/main/java9/module-info.java .
This was only added late on Aug 25th 2021 - maybe your lanterna.jar predates this change?
