### ISSUE TITLE
Cannot run program "stty.exe"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mabe02/lanterna#87]
```
Lanterna is trying to execute program stty.exe and it does not exist at my 
computer windows 8 64.


[s[5001;5001H[6n[u[?1049hException in thread "main" java.io.IOException: 
Cannot run program "stty.exe": CreateProcess error=2, O sistema não pode 
encontrar o arquivo especificado
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:460)
	at com.googlecode.lanterna.terminal.text.CygwinTerminal.exec(CygwinTerminal.java:158)
	at com.googlecode.lanterna.terminal.text.CygwinTerminal.sttyCBreak(CygwinTerminal.java:129)
	at com.googlecode.lanterna.terminal.text.CygwinTerminal.setCBreak(CygwinTerminal.java:101)
	at com.googlecode.lanterna.terminal.text.CygwinTerminal.enterPrivateMode(CygwinTerminal.java:78)
	at com.googlecode.lanterna.screen.Screen.startScreen(Screen.java:202)
	at TCPServerLanterna.main(TCPServerLanterna.java:34)
```

Original issue reported on code.google.com by `miche...@gmail.com` on 23 Oct 2013 at 7:02

**Comment by mabe02** [comment]
Lanterna 3 has a built-in Telnet server now finally. Running Lanterna natively in Window console is not supported due to me being unable to control things like input mode (enable icanon mode for example), echo and other settings without invoking native code. So far we've managed without native code and I'd like it to continue that way. Cygwin is partially supported but there too we have issues with modifying the TTY.
